//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:01:08 PM BRT 
//


package br.inf.portalfiscal.cte.send;

import com.softart.dfe.interfaces.xml.generic.XML;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfEspecie complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="InfEspecie"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tpEspecie"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;whiteSpace value="preserve"/&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vEspecie" type="{http://www.portalfiscal.inf.br/cte}TDec_1302" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfEspecie", propOrder = {
        "tpEspecie",
        "vEspecie"
})
public class InfEspecie
        implements XML {

    @XmlElement(required = true)
    protected String tpEspecie;
    protected String vEspecie;

    /**
     * Gets the value of the tpEspecie property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTpEspecie() {
        return tpEspecie;
    }

    /**
     * Sets the value of the tpEspecie property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTpEspecie(String value) {
        this.tpEspecie = value;
    }

    public boolean isSetTpEspecie() {
        return (this.tpEspecie != null);
    }

    /**
     * Gets the value of the vEspecie property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVEspecie() {
        return vEspecie;
    }

    /**
     * Sets the value of the vEspecie property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVEspecie(String value) {
        this.vEspecie = value;
    }

    public boolean isSetVEspecie() {
        return (this.vEspecie != null);
    }

}
