//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:01:08 PM BRT 
//


package br.inf.portalfiscal.cte.send;

import org.dfe.interfaces.xml.generic.XML;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Occ complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Occ"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serie" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nOcc"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;whiteSpace value="preserve"/&gt;
 *               &lt;pattern value="[1-9]{1}[0-9]{0,5}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dEmi" type="{http://www.portalfiscal.inf.br/cte}TData"/&gt;
 *         &lt;element name="emiOcc" type="{http://www.portalfiscal.inf.br/cte}EmiOcc"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Occ", propOrder = {
        "serie",
        "nOcc",
        "dEmi",
        "emiOcc"
})
public class Occ
        implements XML {

    protected String serie;
    @XmlElement(required = true)
    protected String nOcc;
    @XmlElement(required = true)
    protected String dEmi;
    @XmlElement(required = true)
    protected EmiOcc emiOcc;

    /**
     * Gets the value of the serie property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    public boolean isSetSerie() {
        return (this.serie != null);
    }

    /**
     * Gets the value of the nOcc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNOcc() {
        return nOcc;
    }

    /**
     * Sets the value of the nOcc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNOcc(String value) {
        this.nOcc = value;
    }

    public boolean isSetNOcc() {
        return (this.nOcc != null);
    }

    /**
     * Gets the value of the dEmi property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDEmi() {
        return dEmi;
    }

    /**
     * Sets the value of the dEmi property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDEmi(String value) {
        this.dEmi = value;
    }

    public boolean isSetDEmi() {
        return (this.dEmi != null);
    }

    /**
     * Gets the value of the emiOcc property.
     *
     * @return possible object is
     * {@link EmiOcc }
     */
    public EmiOcc getEmiOcc() {
        return emiOcc;
    }

    /**
     * Sets the value of the emiOcc property.
     *
     * @param value allowed object is
     *              {@link EmiOcc }
     */
    public void setEmiOcc(EmiOcc value) {
        this.emiOcc = value;
    }

    public boolean isSetEmiOcc() {
        return (this.emiOcc != null);
    }

}
