package br.inf.portalfiscal.cte4.wsdl.query_situation.mt.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 *
 */
@WebService(name = "CteConsultaSoap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeConsultaV4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.cte.send400.ObjectFactory.class
})
public interface CteConsultaSoap12 {


    /**
     *
     * @param cteDadosMsg
     * @return returns jakarta.xml.ws.Response<br.inf.portalfiscal.cte4.wsdl.query_situation.mt.prod.CteConsultaCTResult>
     */
    @WebMethod(operationName = "cteConsulta", action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/CTeConsultaV4")
    public Response<CteConsultaCTResult> cteConsultaAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeConsultaV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg);

    /**
     *
     * @param asyncHandler
     * @param cteDadosMsg
     * @return returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "cteConsulta", action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/CTeConsultaV4")
    public Future<?> cteConsultaAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeConsultaV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg,
            @WebParam(name = "cteConsultaResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<CteConsultaCTResult> asyncHandler);

    /**
     *
     * @param cteDadosMsg
     * @return returns br.inf.portalfiscal.cte4.wsdl.query_situation.mt.prod.CteConsultaCTResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/CTeConsultaV4")
    @WebResult(name = "cteConsultaCTResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeConsultaV4", partName = "cteConsultaCTResult")
    public CteConsultaCTResult cteConsulta(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeConsultaV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg);

}
