package br.inf.portalfiscal.cte4.wsdl.status_service.mg.hom;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 *
 */
@WebService(name = "CTeStatusServicoV4Soap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.cte.send400.ObjectFactory.class
})
public interface CTeStatusServicoV4Soap12 {


    /**
     *
     * @param cteDadosMsg
     * @return returns jakarta.xml.ws.Response<br.inf.portalfiscal.cte4.wsdl.status_service.mg.hom.CteStatusServicoCTResult>
     */
    @WebMethod(operationName = "cteStatusServicoCT", action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4/cteStatusServicoCT")
    public Response<CteStatusServicoCTResult> cteStatusServicoCTAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg);

    /**
     *
     * @param asyncHandler
     * @param cteDadosMsg
     * @return returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "cteStatusServicoCT", action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4/cteStatusServicoCT")
    public Future<?> cteStatusServicoCTAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg,
            @WebParam(name = "cteStatusServicoCTResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<CteStatusServicoCTResult> asyncHandler);

    /**
     *
     * @param cteDadosMsg
     * @return returns br.inf.portalfiscal.cte4.wsdl.status_service.mg.hom.CteStatusServicoCTResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4/cteStatusServicoCT")
    @WebResult(name = "cteStatusServicoCTResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4", partName = "cteStatusServicoCTResult")
    @Action(input = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4/cteStatusServicoCT", output = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4/CTeStatusServicoV4Soap12/cteStatusServicoCTResponse")
    public CteStatusServicoCTResult cteStatusServicoCT(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeStatusServicoV4", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg);

}
