package br.inf.portalfiscal.nfe.wsdl.query_protocol.ba.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 *
 */
@WebService(name = "NFeConsultaProtocolo4Soap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.nfe.send.ObjectFactory.class
})
public interface NFeConsultaProtocolo4Soap {


    /**
     * Serviço destinado à consulta da NF-e.
     *
     * @param nfeDadosMsg
     * @return returns jakarta.xml.ws.Response<br.inf.portalfiscal.nfe.wsdl.query_protocol.ba.prod.NfeResultMsg>
     */
    @WebMethod(operationName = "NFeConsultaNF", action = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF")
    public Response<NfeResultMsg> nFeConsultaNFAsync(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg);

    /**
     * Serviço destinado à consulta da NF-e.
     *
     * @param asyncHandler
     * @param nfeDadosMsg
     * @return returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "NFeConsultaNF", action = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF")
    public Future<?> nFeConsultaNFAsync(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "NFeConsultaNFResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<NfeResultMsg> asyncHandler);

    /**
     * Serviço destinado à consulta da NF-e.
     *
     * @param nfeDadosMsg
     * @return returns br.inf.portalfiscal.nfe.wsdl.query_protocol.ba.prod.NfeResultMsg
     */
    @WebMethod(operationName = "NFeConsultaNF", action = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF")
    @WebResult(name = "nfeResultMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", partName = "nfeConsultaNFResult")
    public NfeResultMsg nFeConsultaNF(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg);

}
