//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 01:10:25 PM BRT 
//


package br.inf.portalfiscal.nfe.send;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * Cada DFe que utilizar deverá utilizar esses tipo no grupo ide
 *
 * <p>Java class for TCompraGov complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TCompraGov"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tpEnteGov" type="{http://www.portalfiscal.inf.br/nfe}TEnteGov"/&gt;
 *         &lt;element name="pRedutor" type="{http://www.portalfiscal.inf.br/nfe}TDec_0302_04"/&gt;
 *         &lt;element name="tpOperGov" type="{http://www.portalfiscal.inf.br/nfe}TOperCompraGov"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TCompraGov", propOrder = {
        "tpEnteGov",
        "pRedutor",
        "tpOperGov"
})
public class TCompraGov
        implements XML {

    @XmlElement(required = true)
    protected String tpEnteGov;
    @XmlElement(required = true)
    protected String pRedutor;
    @XmlElement(required = true)
    protected String tpOperGov;

    /**
     * Gets the value of the tpEnteGov property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getTpEnteGov() {
        return tpEnteGov;
    }

    /**
     * Sets the value of the tpEnteGov property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setTpEnteGov(String value) {
        this.tpEnteGov = value;
    }

    public boolean isSetTpEnteGov() {
        return (this.tpEnteGov != null);
    }

    /**
     * Gets the value of the pRedutor property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getPRedutor() {
        return pRedutor;
    }

    /**
     * Sets the value of the pRedutor property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setPRedutor(String value) {
        this.pRedutor = value;
    }

    public boolean isSetPRedutor() {
        return (this.pRedutor != null);
    }

    /**
     * Gets the value of the tpOperGov property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getTpOperGov() {
        return tpOperGov;
    }

    /**
     * Sets the value of the tpOperGov property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setTpOperGov(String value) {
        this.tpOperGov = value;
    }

    public boolean isSetTpOperGov() {
        return (this.tpOperGov != null);
    }

}
