//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.09 at 01:10:25 PM BRT 
//


package br.inf.portalfiscal.nfe.send;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * Grupo de informações de totais do Imposto Seletivo
 *
 * <p>Java class for TISTot complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TISTot"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vIS" type="{http://www.portalfiscal.inf.br/nfe}TDec1302"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TISTot", propOrder = {
        "vis"
})
public class TISTot
        implements XML {

    @XmlElement(name = "vIS", required = true)
    protected String vis;

    /**
     * Gets the value of the vis property.
     *
     * @return possible object is
     * {@link String }
     *
     */
    public String getVIS() {
        return vis;
    }

    /**
     * Sets the value of the vis property.
     *
     * @param value allowed object is
     *              {@link String }
     *
     */
    public void setVIS(String value) {
        this.vis = value;
    }

    public boolean isSetVIS() {
        return (this.vis != null);
    }

}
