package br.inf.portalfiscal.cte4.wsdl.reception_gtve.mt.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 *
 */
@WebService(name = "CTeRecepcaoGTVeSoap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.cte.send400.ObjectFactory.class
})
public interface CTeRecepcaoGTVeSoap12 {


    /**
     *
     * @param cteDadosMsg
     * @return returns jakarta.xml.ws.Response<br.inf.portalfiscal.cte4.wsdl.reception_gtve.mt.prod.CteRecepcaoGTVeResult>
     */
    @WebMethod(operationName = "cteRecepcaoGTVe", action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVe/CTeRecepcaoGTVeV4")
    public Response<CteRecepcaoGTVeResult> cteRecepcaoGTVeAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4", partName = "cteDadosMsg")
            String cteDadosMsg);

    /**
     *
     * @param asyncHandler
     * @param cteDadosMsg
     * @return returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "cteRecepcaoGTVe", action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVe/CTeRecepcaoGTVeV4")
    public Future<?> cteRecepcaoGTVeAsync(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4", partName = "cteDadosMsg")
            String cteDadosMsg,
            @WebParam(name = "cteRecepcaoGTVeResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<CteRecepcaoGTVeResult> asyncHandler);

    /**
     *
     * @param cteDadosMsg
     * @return returns br.inf.portalfiscal.cte4.wsdl.reception_gtve.mt.prod.CteRecepcaoGTVeResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVe/CTeRecepcaoGTVeV4")
    @WebResult(name = "cteRecepcaoGTVeResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4", partName = "cteRecepcaoGTVeResult")
    public CteRecepcaoGTVeResult cteRecepcaoGTVe(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoGTVeV4", partName = "cteDadosMsg")
            String cteDadosMsg);

}
