package br.inf.portalfiscal.cte.wsdl.status_service.ms.hom;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * Serviço destinado à consulta do status do
 * serviço prestado pelo Portal da Secretaria de Fazenda Estadual.
 * <p>
 * <p>
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 */
@WebServiceClient(name = "CteStatusServico", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", wsdlLocation = "https://homologacao.cte.ms.gov.br/ws/CteStatusServico?wsdl")
public class CteStatusServico
        extends Service {

    private static final URL CTESTATUSSERVICO_WSDL_LOCATION;
    private static final WebServiceException CTESTATUSSERVICO_EXCEPTION;
    private static final QName CTESTATUSSERVICO_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServico");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://homologacao.cte.ms.gov.br/ws/CteStatusServico?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTESTATUSSERVICO_WSDL_LOCATION = url;
        CTESTATUSSERVICO_EXCEPTION = e;
    }

    public CteStatusServico() {
        super(__getWsdlLocation(), CTESTATUSSERVICO_QNAME);
    }

    public CteStatusServico(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTESTATUSSERVICO_QNAME, features);
    }

    public CteStatusServico(URL wsdlLocation) {
        super(wsdlLocation, CTESTATUSSERVICO_QNAME);
    }

    public CteStatusServico(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTESTATUSSERVICO_QNAME, features);
    }

    public CteStatusServico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteStatusServico(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CteStatusServicoSoap12
     */
    @WebEndpoint(name = "CteStatusServicoSoap12")
    public CteStatusServicoSoap12 getCteStatusServicoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServicoSoap12"), CteStatusServicoSoap12.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CteStatusServicoSoap12
     */
    @WebEndpoint(name = "CteStatusServicoSoap12")
    public CteStatusServicoSoap12 getCteStatusServicoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServicoSoap12"), CteStatusServicoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTESTATUSSERVICO_EXCEPTION != null) {
            throw CTESTATUSSERVICO_EXCEPTION;
        }
        return CTESTATUSSERVICO_WSDL_LOCATION;
    }

}
