package br.inf.portalfiscal.cte.wsdl.reception_sync.svsp.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 */
@WebService(name = "CTeRecepcaoSincSoap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSinc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.cte.send.ObjectFactory.class
})
public interface CTeRecepcaoSincSoap12 {


    /**
     * Recepção síncrona do CTe (modelo 57)
     *
     * @param cteDadosMsg
     * @return returns br.inf.portalfiscal.cte.wsdl.reception_sync.svsp.prod.CteRecepcaoSincResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSinc/cteRecepcaoSinc")
    @WebResult(name = "cteRecepcaoSincResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSinc", partName = "cteRecepcaoSincResult")
    public CteRecepcaoSincResult cteRecepcaoSinc(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeRecepcaoSinc", partName = "cteDadosMsg")
            String cteDadosMsg);

}
