package br.inf.portalfiscal.mdfe.wsdl.query_unclosed.svrs.prod;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 */
@WebServiceClient(name = "MDFeConsNaoEnc", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc", wsdlLocation = "https://mdfe.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx?wsdl")
public class MDFeConsNaoEnc
        extends Service {

    private static final URL MDFECONSNAOENC_WSDL_LOCATION;
    private static final WebServiceException MDFECONSNAOENC_EXCEPTION;
    private static final QName MDFECONSNAOENC_QNAME = new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc", "MDFeConsNaoEnc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mdfe.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDFECONSNAOENC_WSDL_LOCATION = url;
        MDFECONSNAOENC_EXCEPTION = e;
    }

    public MDFeConsNaoEnc() {
        super(__getWsdlLocation(), MDFECONSNAOENC_QNAME);
    }

    public MDFeConsNaoEnc(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDFECONSNAOENC_QNAME, features);
    }

    public MDFeConsNaoEnc(URL wsdlLocation) {
        super(wsdlLocation, MDFECONSNAOENC_QNAME);
    }

    public MDFeConsNaoEnc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDFECONSNAOENC_QNAME, features);
    }

    public MDFeConsNaoEnc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDFeConsNaoEnc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns MDFeConsNaoEncSoap12
     */
    @WebEndpoint(name = "MDFeConsNaoEncSoap12")
    public MDFeConsNaoEncSoap12 getMDFeConsNaoEncSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc", "MDFeConsNaoEncSoap12"), MDFeConsNaoEncSoap12.class);
    }

    /**
     * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MDFeConsNaoEncSoap12
     */
    @WebEndpoint(name = "MDFeConsNaoEncSoap12")
    public MDFeConsNaoEncSoap12 getMDFeConsNaoEncSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeConsNaoEnc", "MDFeConsNaoEncSoap12"), MDFeConsNaoEncSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDFECONSNAOENC_EXCEPTION != null) {
            throw MDFECONSNAOENC_EXCEPTION;
        }
        return MDFECONSNAOENC_WSDL_LOCATION;
    }

}
