//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:01:08 PM BRT 
//


package br.inf.portalfiscal.nfe.gtin;

import org.dfe.interfaces.xml.generic.XML;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.util.ArrayList;
import java.util.List;


/**
 * Tipo Retorno da Consulta pública Cadastro Centralizado de GTIN
 *
 * <p>Java class for TRetConsGTIN complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRetConsGTIN"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="verAplic" type="{http://www.portalfiscal.inf.br/nfe}TVerAplic"/&gt;
 *         &lt;element name="cStat" type="{http://www.portalfiscal.inf.br/nfe}TStat"/&gt;
 *         &lt;element name="xMotivo" type="{http://www.portalfiscal.inf.br/nfe}TMotivo"/&gt;
 *         &lt;element name="dhResp" type="{http://www.portalfiscal.inf.br/nfe}TDateTimeUTC"/&gt;
 *         &lt;element name="GTIN" type="{http://www.portalfiscal.inf.br/nfe}TCodGTIN" minOccurs="0"/&gt;
 *         &lt;element name="tpGTIN" type="{http://www.portalfiscal.inf.br/nfe}TTpGTIN" minOccurs="0"/&gt;
 *         &lt;element name="xProd" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="500"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NCM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
 *               &lt;pattern value="[0-9]{8}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CEST" maxOccurs="3" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
 *               &lt;pattern value="[0-9]{7}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="versao" use="required" type="{http://www.portalfiscal.inf.br/nfe}TVerConsGTIN" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRetConsGTIN", propOrder = {
        "verAplic",
        "cStat",
        "xMotivo",
        "dhResp",
        "gtin",
        "tpGTIN",
        "xProd",
        "ncm",
        "cest"
})
public class TRetConsGTIN
        implements XML {

    @XmlElement(required = true)
    protected String verAplic;
    @XmlElement(required = true)
    protected String cStat;
    @XmlElement(required = true)
    protected String xMotivo;
    @XmlElement(required = true)
    protected String dhResp;
    @XmlElement(name = "GTIN")
    protected String gtin;
    protected String tpGTIN;
    protected String xProd;
    @XmlElement(name = "NCM")
    protected String ncm;
    @XmlElement(name = "CEST")
    protected List<String> cest;
    @XmlAttribute(name = "versao", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versao;

    /**
     * Gets the value of the verAplic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVerAplic() {
        return verAplic;
    }

    /**
     * Sets the value of the verAplic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVerAplic(String value) {
        this.verAplic = value;
    }

    public boolean isSetVerAplic() {
        return (this.verAplic != null);
    }

    /**
     * Gets the value of the cStat property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCStat() {
        return cStat;
    }

    /**
     * Sets the value of the cStat property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCStat(String value) {
        this.cStat = value;
    }

    public boolean isSetCStat() {
        return (this.cStat != null);
    }

    /**
     * Gets the value of the xMotivo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXMotivo() {
        return xMotivo;
    }

    /**
     * Sets the value of the xMotivo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXMotivo(String value) {
        this.xMotivo = value;
    }

    public boolean isSetXMotivo() {
        return (this.xMotivo != null);
    }

    /**
     * Gets the value of the dhResp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDhResp() {
        return dhResp;
    }

    /**
     * Sets the value of the dhResp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDhResp(String value) {
        this.dhResp = value;
    }

    public boolean isSetDhResp() {
        return (this.dhResp != null);
    }

    /**
     * Gets the value of the gtin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGTIN() {
        return gtin;
    }

    /**
     * Sets the value of the gtin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGTIN(String value) {
        this.gtin = value;
    }

    public boolean isSetGTIN() {
        return (this.gtin != null);
    }

    /**
     * Gets the value of the tpGTIN property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTpGTIN() {
        return tpGTIN;
    }

    /**
     * Sets the value of the tpGTIN property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTpGTIN(String value) {
        this.tpGTIN = value;
    }

    public boolean isSetTpGTIN() {
        return (this.tpGTIN != null);
    }

    /**
     * Gets the value of the xProd property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXProd() {
        return xProd;
    }

    /**
     * Sets the value of the xProd property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXProd(String value) {
        this.xProd = value;
    }

    public boolean isSetXProd() {
        return (this.xProd != null);
    }

    /**
     * Gets the value of the ncm property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNCM() {
        return ncm;
    }

    /**
     * Sets the value of the ncm property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNCM(String value) {
        this.ncm = value;
    }

    public boolean isSetNCM() {
        return (this.ncm != null);
    }

    /**
     * Gets the value of the cest property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the cest property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCEST().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getCEST() {
        if (cest == null) {
            cest = new ArrayList<>();
        }
        return this.cest;
    }

    public boolean isSetCEST() {
        return ((this.cest != null) && (!this.cest.isEmpty()));
    }

    public void unsetCEST() {
        this.cest = null;
    }

    /**
     * Gets the value of the versao property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersao(String value) {
        this.versao = value;
    }

    public boolean isSetVersao() {
        return (this.versao != null);
    }

}
