package br.inf.portalfiscal.cte.wsdl.reception_gtve.svsp.prod;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * Serviço destinado à recepção de mensagens de
 * GTVe (modelo 64).
 * <p>
 * <p>
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 */
@WebServiceClient(name = "CteRecepcaoGTVe", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoGTVe", wsdlLocation = "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcaoGTVe.asmx?wsdl")
public class CteRecepcaoGTVe
        extends Service {

    private static final URL CTERECEPCAOGTVE_WSDL_LOCATION;
    private static final WebServiceException CTERECEPCAOGTVE_EXCEPTION;
    private static final QName CTERECEPCAOGTVE_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoGTVe", "CteRecepcaoGTVe");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcaoGTVe.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTERECEPCAOGTVE_WSDL_LOCATION = url;
        CTERECEPCAOGTVE_EXCEPTION = e;
    }

    public CteRecepcaoGTVe() {
        super(__getWsdlLocation(), CTERECEPCAOGTVE_QNAME);
    }

    public CteRecepcaoGTVe(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTERECEPCAOGTVE_QNAME, features);
    }

    public CteRecepcaoGTVe(URL wsdlLocation) {
        super(wsdlLocation, CTERECEPCAOGTVE_QNAME);
    }

    public CteRecepcaoGTVe(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTERECEPCAOGTVE_QNAME, features);
    }

    public CteRecepcaoGTVe(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteRecepcaoGTVe(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CteRecepcaoGTVeSoap12
     */
    @WebEndpoint(name = "CteRecepcaoGTVeSoap12")
    public CteRecepcaoGTVeSoap12 getCteRecepcaoGTVeSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoGTVe", "CteRecepcaoGTVeSoap12"), CteRecepcaoGTVeSoap12.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CteRecepcaoGTVeSoap12
     */
    @WebEndpoint(name = "CteRecepcaoGTVeSoap12")
    public CteRecepcaoGTVeSoap12 getCteRecepcaoGTVeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoGTVe", "CteRecepcaoGTVeSoap12"), CteRecepcaoGTVeSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTERECEPCAOGTVE_EXCEPTION != null) {
            throw CTERECEPCAOGTVE_EXCEPTION;
        }
        return CTERECEPCAOGTVE_WSDL_LOCATION;
    }

}
