<definitions
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:tns="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        targetNamespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico" name="CTeStatusServicoV4">
    <types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"
                   targetNamespace="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico">
            <xs:element name="cteDadosMsg">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:any processContents="lax" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cteStatusServicoCTResult">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:any processContents="lax" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </types>
    <message name="cteStatusServicoCT">
        <part name="cteDadosMsg" element="tns:cteDadosMsg"/>
    </message>
    <message name="cteStatusServicoCTResponse">
        <part name="cteStatusServicoCTResult" element="tns:cteStatusServicoCTResult"/>
    </message>
    <portType name="CTeStatusServicoV4Soap12">
        <operation name="cteStatusServicoCT">
            <input wsam:Action="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico/cteStatusServicoCT"
                   message="tns:cteStatusServicoCT"/>
            <output wsam:Action="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico/CTeStatusServicoV4Soap12/cteStatusServicoCTResponse"
                    message="tns:cteStatusServicoCTResponse"/>
        </operation>
    </portType>
    <binding name="CTeStatusServicoV4Soap12Binding" type="tns:CTeStatusServicoV4Soap12">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="cteStatusServicoCT">
            <soap12:operation soapAction="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico/cteStatusServicoCT"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CTeStatusServicoV4">
        <port name="CTeStatusServicoV4Soap12" binding="tns:CTeStatusServicoV4Soap12Binding">
            <soap12:address location="https://cte.fazenda.mg.gov.br:443/cte/services/CTeStatusServicoV4"/>
        </port>
    </service>
</definitions>