//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:01:08 PM BRT 
//


package br.inf.portalfiscal.cte.send400;

import org.dfe.interfaces.xml.generic.XML;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Aereo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Aereo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nMinu" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;whiteSpace value="preserve"/&gt;
 *               &lt;pattern value="[0-9]{9}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nOCA" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;whiteSpace value="preserve"/&gt;
 *               &lt;pattern value="[0-9]{11}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dPrevAereo" type="{http://www.portalfiscal.inf.br/cte}TData"/&gt;
 *         &lt;element name="natCarga"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="xDime" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
 *                         &lt;minLength value="5"/&gt;
 *                         &lt;maxLength value="14"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="cInfManu" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;whiteSpace value="preserve"/&gt;
 *                         &lt;enumeration value="01"/&gt;
 *                         &lt;enumeration value="02"/&gt;
 *                         &lt;enumeration value="03"/&gt;
 *                         &lt;enumeration value="04"/&gt;
 *                         &lt;enumeration value="05"/&gt;
 *                         &lt;enumeration value="06"/&gt;
 *                         &lt;enumeration value="07"/&gt;
 *                         &lt;enumeration value="08"/&gt;
 *                         &lt;enumeration value="09"/&gt;
 *                         &lt;enumeration value="10"/&gt;
 *                         &lt;enumeration value="11"/&gt;
 *                         &lt;enumeration value="12"/&gt;
 *                         &lt;enumeration value="13"/&gt;
 *                         &lt;enumeration value="14"/&gt;
 *                         &lt;enumeration value="15"/&gt;
 *                         &lt;enumeration value="99"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tarifa"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CL"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;length value="1"/&gt;
 *                         &lt;whiteSpace value="preserve"/&gt;
 *                         &lt;pattern value="M"/&gt;
 *                         &lt;pattern value="G"/&gt;
 *                         &lt;pattern value="E"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="cTar" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="4"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="vTar" type="{http://www.portalfiscal.inf.br/cte}TDec_1302"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="peri" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="nONU"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;whiteSpace value="preserve"/&gt;
 *                         &lt;pattern value="[0-9]{4}|ND"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="qTotEmb"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
 *                         &lt;minLength value="1"/&gt;
 *                         &lt;maxLength value="20"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="infTotAP"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="qTotProd" type="{http://www.portalfiscal.inf.br/cte}TDec_1104"/&gt;
 *                             &lt;element name="uniAP"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                   &lt;maxLength value="1"/&gt;
 *                                   &lt;enumeration value="1"/&gt;
 *                                   &lt;enumeration value="2"/&gt;
 *                                   &lt;enumeration value="3"/&gt;
 *                                   &lt;enumeration value="4"/&gt;
 *                                   &lt;enumeration value="5"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aereo", propOrder = {
        "nMinu",
        "noca",
        "dPrevAereo",
        "natCarga",
        "tarifa",
        "peri"
})
public class Aereo
        implements XML {

    protected String nMinu;
    @XmlElement(name = "nOCA")
    protected String noca;
    @XmlElement(required = true)
    protected String dPrevAereo;
    @XmlElement(required = true)
    protected NatCarga natCarga;
    @XmlElement(required = true)
    protected Tarifa tarifa;
    protected List<Peri> peri;

    /**
     * Gets the value of the nMinu property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNMinu() {
        return nMinu;
    }

    /**
     * Sets the value of the nMinu property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNMinu(String value) {
        this.nMinu = value;
    }

    public boolean isSetNMinu() {
        return (this.nMinu != null);
    }

    /**
     * Gets the value of the noca property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNOCA() {
        return noca;
    }

    /**
     * Sets the value of the noca property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNOCA(String value) {
        this.noca = value;
    }

    public boolean isSetNOCA() {
        return (this.noca != null);
    }

    /**
     * Gets the value of the dPrevAereo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDPrevAereo() {
        return dPrevAereo;
    }

    /**
     * Sets the value of the dPrevAereo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDPrevAereo(String value) {
        this.dPrevAereo = value;
    }

    public boolean isSetDPrevAereo() {
        return (this.dPrevAereo != null);
    }

    /**
     * Gets the value of the natCarga property.
     *
     * @return possible object is
     * {@link NatCarga }
     */
    public NatCarga getNatCarga() {
        return natCarga;
    }

    /**
     * Sets the value of the natCarga property.
     *
     * @param value allowed object is
     *              {@link NatCarga }
     */
    public void setNatCarga(NatCarga value) {
        this.natCarga = value;
    }

    public boolean isSetNatCarga() {
        return (this.natCarga != null);
    }

    /**
     * Gets the value of the tarifa property.
     *
     * @return possible object is
     * {@link Tarifa }
     */
    public Tarifa getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     *
     * @param value allowed object is
     *              {@link Tarifa }
     */
    public void setTarifa(Tarifa value) {
        this.tarifa = value;
    }

    public boolean isSetTarifa() {
        return (this.tarifa != null);
    }

    /**
     * Gets the value of the peri property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the peri property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeri().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Peri }
     */
    public List<Peri> getPeri() {
        if (peri == null) {
            peri = new ArrayList<>();
        }
        return this.peri;
    }

    public boolean isSetPeri() {
        return ((this.peri != null) && (!this.peri.isEmpty()));
    }

    public void unsetPeri() {
        this.peri = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="xDime" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
     *               &lt;minLength value="5"/&gt;
     *               &lt;maxLength value="14"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="cInfManu" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;whiteSpace value="preserve"/&gt;
     *               &lt;enumeration value="01"/&gt;
     *               &lt;enumeration value="02"/&gt;
     *               &lt;enumeration value="03"/&gt;
     *               &lt;enumeration value="04"/&gt;
     *               &lt;enumeration value="05"/&gt;
     *               &lt;enumeration value="06"/&gt;
     *               &lt;enumeration value="07"/&gt;
     *               &lt;enumeration value="08"/&gt;
     *               &lt;enumeration value="09"/&gt;
     *               &lt;enumeration value="10"/&gt;
     *               &lt;enumeration value="11"/&gt;
     *               &lt;enumeration value="12"/&gt;
     *               &lt;enumeration value="13"/&gt;
     *               &lt;enumeration value="14"/&gt;
     *               &lt;enumeration value="15"/&gt;
     *               &lt;enumeration value="99"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "xDime",
            "cInfManu"
    })
    public static class NatCarga
            implements XML {

        protected String xDime;
        protected List<String> cInfManu;

        /**
         * Gets the value of the xDime property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getXDime() {
            return xDime;
        }

        /**
         * Sets the value of the xDime property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setXDime(String value) {
            this.xDime = value;
        }

        public boolean isSetXDime() {
            return (this.xDime != null);
        }

        /**
         * Gets the value of the cInfManu property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the cInfManu property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCInfManu().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getCInfManu() {
            if (cInfManu == null) {
                cInfManu = new ArrayList<>();
            }
            return this.cInfManu;
        }

        public boolean isSetCInfManu() {
            return ((this.cInfManu != null) && (!this.cInfManu.isEmpty()));
        }

        public void unsetCInfManu() {
            this.cInfManu = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="nONU"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;whiteSpace value="preserve"/&gt;
     *               &lt;pattern value="[0-9]{4}|ND"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="qTotEmb"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="infTotAP"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="qTotProd" type="{http://www.portalfiscal.inf.br/cte}TDec_1104"/&gt;
     *                   &lt;element name="uniAP"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
     *                         &lt;minLength value="1"/&gt;
     *                         &lt;maxLength value="1"/&gt;
     *                         &lt;enumeration value="1"/&gt;
     *                         &lt;enumeration value="2"/&gt;
     *                         &lt;enumeration value="3"/&gt;
     *                         &lt;enumeration value="4"/&gt;
     *                         &lt;enumeration value="5"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "nonu",
            "qTotEmb",
            "infTotAP"
    })
    public static class Peri
            implements XML {

        @XmlElement(name = "nONU", required = true)
        protected String nonu;
        @XmlElement(required = true)
        protected String qTotEmb;
        @XmlElement(required = true)
        protected InfTotAP infTotAP;

        /**
         * Gets the value of the nonu property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getNONU() {
            return nonu;
        }

        /**
         * Sets the value of the nonu property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setNONU(String value) {
            this.nonu = value;
        }

        public boolean isSetNONU() {
            return (this.nonu != null);
        }

        /**
         * Gets the value of the qTotEmb property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getQTotEmb() {
            return qTotEmb;
        }

        /**
         * Sets the value of the qTotEmb property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setQTotEmb(String value) {
            this.qTotEmb = value;
        }

        public boolean isSetQTotEmb() {
            return (this.qTotEmb != null);
        }

        /**
         * Gets the value of the infTotAP property.
         *
         * @return possible object is
         * {@link InfTotAP }
         */
        public InfTotAP getInfTotAP() {
            return infTotAP;
        }

        /**
         * Sets the value of the infTotAP property.
         *
         * @param value allowed object is
         *              {@link InfTotAP }
         */
        public void setInfTotAP(InfTotAP value) {
            this.infTotAP = value;
        }

        public boolean isSetInfTotAP() {
            return (this.infTotAP != null);
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="qTotProd" type="{http://www.portalfiscal.inf.br/cte}TDec_1104"/&gt;
         *         &lt;element name="uniAP"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
         *               &lt;minLength value="1"/&gt;
         *               &lt;maxLength value="1"/&gt;
         *               &lt;enumeration value="1"/&gt;
         *               &lt;enumeration value="2"/&gt;
         *               &lt;enumeration value="3"/&gt;
         *               &lt;enumeration value="4"/&gt;
         *               &lt;enumeration value="5"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "qTotProd",
                "uniAP"
        })
        public static class InfTotAP
                implements XML {

            @XmlElement(required = true)
            protected String qTotProd;
            @XmlElement(required = true)
            protected String uniAP;

            /**
             * Gets the value of the qTotProd property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getQTotProd() {
                return qTotProd;
            }

            /**
             * Sets the value of the qTotProd property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setQTotProd(String value) {
                this.qTotProd = value;
            }

            public boolean isSetQTotProd() {
                return (this.qTotProd != null);
            }

            /**
             * Gets the value of the uniAP property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getUniAP() {
                return uniAP;
            }

            /**
             * Sets the value of the uniAP property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setUniAP(String value) {
                this.uniAP = value;
            }

            public boolean isSetUniAP() {
                return (this.uniAP != null);
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CL"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;length value="1"/&gt;
     *               &lt;whiteSpace value="preserve"/&gt;
     *               &lt;pattern value="M"/&gt;
     *               &lt;pattern value="G"/&gt;
     *               &lt;pattern value="E"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="cTar" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString"&gt;
     *               &lt;minLength value="1"/&gt;
     *               &lt;maxLength value="4"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="vTar" type="{http://www.portalfiscal.inf.br/cte}TDec_1302"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "cl",
            "cTar",
            "vTar"
    })
    public static class Tarifa
            implements XML {

        @XmlElement(name = "CL", required = true)
        protected String cl;
        protected String cTar;
        @XmlElement(required = true)
        protected String vTar;

        /**
         * Gets the value of the cl property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCL() {
            return cl;
        }

        /**
         * Sets the value of the cl property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCL(String value) {
            this.cl = value;
        }

        public boolean isSetCL() {
            return (this.cl != null);
        }

        /**
         * Gets the value of the cTar property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCTar() {
            return cTar;
        }

        /**
         * Sets the value of the cTar property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCTar(String value) {
            this.cTar = value;
        }

        public boolean isSetCTar() {
            return (this.cTar != null);
        }

        /**
         * Gets the value of the vTar property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getVTar() {
            return vTar;
        }

        /**
         * Sets the value of the vTar property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setVTar(String value) {
            this.vTar = value;
        }

        public boolean isSetVTar() {
            return (this.vTar != null);
        }

    }

}
