//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.05 at 02:48:22 PM BRT 
//


package br.inf.portalfiscal.cte.send400;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * Tipo Devolução Tributo
 *
 * <p>Java class for TDevTrib complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TDevTrib"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vDevTrib" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDevTrib", propOrder = {
        "vDevTrib"
})
public class TDevTrib
        implements XML {

    @XmlElement(required = true)
    protected String vDevTrib;

    /**
     * Gets the value of the vDevTrib property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVDevTrib() {
        return vDevTrib;
    }

    /**
     * Sets the value of the vDevTrib property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVDevTrib(String value) {
        this.vDevTrib = value;
    }

    public boolean isSetVDevTrib() {
        return (this.vDevTrib != null);
    }

}
