//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.05 at 02:48:22 PM BRT 
//


package br.inf.portalfiscal.cte.send400;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * Tipo Monofasia
 *
 * <p>Java class for TMonofasia complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TMonofasia"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qBCMono" type="{http://www.portalfiscal.inf.br/cte}TDec_1104Op"/&gt;
 *         &lt;element name="adRemIBS" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *         &lt;element name="adRemCBS" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *         &lt;element name="vIBSMono" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;element name="vCBSMono" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="qBCMonoReten" type="{http://www.portalfiscal.inf.br/cte}TDec_1104Op"/&gt;
 *           &lt;element name="adRemIBSReten" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *           &lt;element name="vIBSMonoReten" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *           &lt;element name="adRemCBSReten" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *           &lt;element name="vCBSMonoReten" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="qBCMonoRet" type="{http://www.portalfiscal.inf.br/cte}TDec_1104Op"/&gt;
 *           &lt;element name="adRemIBSRet" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *           &lt;element name="vIBSMonoRet" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *           &lt;element name="adRemCBSRet" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *           &lt;element name="vCBSMonoRet" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence minOccurs="0"&gt;
 *           &lt;element name="pDifIBS" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *           &lt;element name="vIBSMonoDif" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *           &lt;element name="pDifCBS" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *           &lt;element name="vCBSMonoDif" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="vTotIBSMonoItem" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *         &lt;element name="vTotCBSMonoItem" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TMonofasia", propOrder = {
        "qbcMono",
        "adRemIBS",
        "adRemCBS",
        "vibsMono",
        "vcbsMono",
        "qbcMonoReten",
        "adRemIBSReten",
        "vibsMonoReten",
        "adRemCBSReten",
        "vcbsMonoReten",
        "qbcMonoRet",
        "adRemIBSRet",
        "vibsMonoRet",
        "adRemCBSRet",
        "vcbsMonoRet",
        "pDifIBS",
        "vibsMonoDif",
        "pDifCBS",
        "vcbsMonoDif",
        "vTotIBSMonoItem",
        "vTotCBSMonoItem"
})
public class TMonofasia
        implements XML {

    @XmlElement(name = "qBCMono", required = true)
    protected String qbcMono;
    @XmlElement(required = true)
    protected String adRemIBS;
    @XmlElement(required = true)
    protected String adRemCBS;
    @XmlElement(name = "vIBSMono", required = true)
    protected String vibsMono;
    @XmlElement(name = "vCBSMono", required = true)
    protected String vcbsMono;
    @XmlElement(name = "qBCMonoReten")
    protected String qbcMonoReten;
    protected String adRemIBSReten;
    @XmlElement(name = "vIBSMonoReten")
    protected String vibsMonoReten;
    protected String adRemCBSReten;
    @XmlElement(name = "vCBSMonoReten")
    protected String vcbsMonoReten;
    @XmlElement(name = "qBCMonoRet")
    protected String qbcMonoRet;
    protected String adRemIBSRet;
    @XmlElement(name = "vIBSMonoRet")
    protected String vibsMonoRet;
    protected String adRemCBSRet;
    @XmlElement(name = "vCBSMonoRet")
    protected String vcbsMonoRet;
    protected String pDifIBS;
    @XmlElement(name = "vIBSMonoDif")
    protected String vibsMonoDif;
    protected String pDifCBS;
    @XmlElement(name = "vCBSMonoDif")
    protected String vcbsMonoDif;
    @XmlElement(required = true)
    protected String vTotIBSMonoItem;
    @XmlElement(required = true)
    protected String vTotCBSMonoItem;

    /**
     * Gets the value of the qbcMono property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQBCMono() {
        return qbcMono;
    }

    /**
     * Sets the value of the qbcMono property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQBCMono(String value) {
        this.qbcMono = value;
    }

    public boolean isSetQBCMono() {
        return (this.qbcMono != null);
    }

    /**
     * Gets the value of the adRemIBS property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemIBS() {
        return adRemIBS;
    }

    /**
     * Sets the value of the adRemIBS property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemIBS(String value) {
        this.adRemIBS = value;
    }

    public boolean isSetAdRemIBS() {
        return (this.adRemIBS != null);
    }

    /**
     * Gets the value of the adRemCBS property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemCBS() {
        return adRemCBS;
    }

    /**
     * Sets the value of the adRemCBS property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemCBS(String value) {
        this.adRemCBS = value;
    }

    public boolean isSetAdRemCBS() {
        return (this.adRemCBS != null);
    }

    /**
     * Gets the value of the vibsMono property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVIBSMono() {
        return vibsMono;
    }

    /**
     * Sets the value of the vibsMono property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVIBSMono(String value) {
        this.vibsMono = value;
    }

    public boolean isSetVIBSMono() {
        return (this.vibsMono != null);
    }

    /**
     * Gets the value of the vcbsMono property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVCBSMono() {
        return vcbsMono;
    }

    /**
     * Sets the value of the vcbsMono property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVCBSMono(String value) {
        this.vcbsMono = value;
    }

    public boolean isSetVCBSMono() {
        return (this.vcbsMono != null);
    }

    /**
     * Gets the value of the qbcMonoReten property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQBCMonoReten() {
        return qbcMonoReten;
    }

    /**
     * Sets the value of the qbcMonoReten property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQBCMonoReten(String value) {
        this.qbcMonoReten = value;
    }

    public boolean isSetQBCMonoReten() {
        return (this.qbcMonoReten != null);
    }

    /**
     * Gets the value of the adRemIBSReten property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemIBSReten() {
        return adRemIBSReten;
    }

    /**
     * Sets the value of the adRemIBSReten property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemIBSReten(String value) {
        this.adRemIBSReten = value;
    }

    public boolean isSetAdRemIBSReten() {
        return (this.adRemIBSReten != null);
    }

    /**
     * Gets the value of the vibsMonoReten property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVIBSMonoReten() {
        return vibsMonoReten;
    }

    /**
     * Sets the value of the vibsMonoReten property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVIBSMonoReten(String value) {
        this.vibsMonoReten = value;
    }

    public boolean isSetVIBSMonoReten() {
        return (this.vibsMonoReten != null);
    }

    /**
     * Gets the value of the adRemCBSReten property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemCBSReten() {
        return adRemCBSReten;
    }

    /**
     * Sets the value of the adRemCBSReten property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemCBSReten(String value) {
        this.adRemCBSReten = value;
    }

    public boolean isSetAdRemCBSReten() {
        return (this.adRemCBSReten != null);
    }

    /**
     * Gets the value of the vcbsMonoReten property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVCBSMonoReten() {
        return vcbsMonoReten;
    }

    /**
     * Sets the value of the vcbsMonoReten property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVCBSMonoReten(String value) {
        this.vcbsMonoReten = value;
    }

    public boolean isSetVCBSMonoReten() {
        return (this.vcbsMonoReten != null);
    }

    /**
     * Gets the value of the qbcMonoRet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getQBCMonoRet() {
        return qbcMonoRet;
    }

    /**
     * Sets the value of the qbcMonoRet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setQBCMonoRet(String value) {
        this.qbcMonoRet = value;
    }

    public boolean isSetQBCMonoRet() {
        return (this.qbcMonoRet != null);
    }

    /**
     * Gets the value of the adRemIBSRet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemIBSRet() {
        return adRemIBSRet;
    }

    /**
     * Sets the value of the adRemIBSRet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemIBSRet(String value) {
        this.adRemIBSRet = value;
    }

    public boolean isSetAdRemIBSRet() {
        return (this.adRemIBSRet != null);
    }

    /**
     * Gets the value of the vibsMonoRet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVIBSMonoRet() {
        return vibsMonoRet;
    }

    /**
     * Sets the value of the vibsMonoRet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVIBSMonoRet(String value) {
        this.vibsMonoRet = value;
    }

    public boolean isSetVIBSMonoRet() {
        return (this.vibsMonoRet != null);
    }

    /**
     * Gets the value of the adRemCBSRet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdRemCBSRet() {
        return adRemCBSRet;
    }

    /**
     * Sets the value of the adRemCBSRet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRemCBSRet(String value) {
        this.adRemCBSRet = value;
    }

    public boolean isSetAdRemCBSRet() {
        return (this.adRemCBSRet != null);
    }

    /**
     * Gets the value of the vcbsMonoRet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVCBSMonoRet() {
        return vcbsMonoRet;
    }

    /**
     * Sets the value of the vcbsMonoRet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVCBSMonoRet(String value) {
        this.vcbsMonoRet = value;
    }

    public boolean isSetVCBSMonoRet() {
        return (this.vcbsMonoRet != null);
    }

    /**
     * Gets the value of the pDifIBS property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPDifIBS() {
        return pDifIBS;
    }

    /**
     * Sets the value of the pDifIBS property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPDifIBS(String value) {
        this.pDifIBS = value;
    }

    public boolean isSetPDifIBS() {
        return (this.pDifIBS != null);
    }

    /**
     * Gets the value of the vibsMonoDif property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVIBSMonoDif() {
        return vibsMonoDif;
    }

    /**
     * Sets the value of the vibsMonoDif property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVIBSMonoDif(String value) {
        this.vibsMonoDif = value;
    }

    public boolean isSetVIBSMonoDif() {
        return (this.vibsMonoDif != null);
    }

    /**
     * Gets the value of the pDifCBS property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPDifCBS() {
        return pDifCBS;
    }

    /**
     * Sets the value of the pDifCBS property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPDifCBS(String value) {
        this.pDifCBS = value;
    }

    public boolean isSetPDifCBS() {
        return (this.pDifCBS != null);
    }

    /**
     * Gets the value of the vcbsMonoDif property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVCBSMonoDif() {
        return vcbsMonoDif;
    }

    /**
     * Sets the value of the vcbsMonoDif property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVCBSMonoDif(String value) {
        this.vcbsMonoDif = value;
    }

    public boolean isSetVCBSMonoDif() {
        return (this.vcbsMonoDif != null);
    }

    /**
     * Gets the value of the vTotIBSMonoItem property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVTotIBSMonoItem() {
        return vTotIBSMonoItem;
    }

    /**
     * Sets the value of the vTotIBSMonoItem property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVTotIBSMonoItem(String value) {
        this.vTotIBSMonoItem = value;
    }

    public boolean isSetVTotIBSMonoItem() {
        return (this.vTotIBSMonoItem != null);
    }

    /**
     * Gets the value of the vTotCBSMonoItem property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVTotCBSMonoItem() {
        return vTotCBSMonoItem;
    }

    /**
     * Sets the value of the vTotCBSMonoItem property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVTotCBSMonoItem(String value) {
        this.vTotCBSMonoItem = value;
    }

    public boolean isSetVTotCBSMonoItem() {
        return (this.vTotCBSMonoItem != null);
    }

}
