//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.05 at 02:48:22 PM BRT 
//


package br.inf.portalfiscal.cte.send400;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * Tipo Redução Base de Cálculo
 *
 * <p>Java class for TRed complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TRed"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pRedAliq" type="{http://www.portalfiscal.inf.br/cte}TDec_0302_04"/&gt;
 *         &lt;element name="pAliqEfet" type="{http://www.portalfiscal.inf.br/cte}TDec1302"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRed", propOrder = {
        "pRedAliq",
        "pAliqEfet"
})
public class TRed
        implements XML {

    @XmlElement(required = true)
    protected String pRedAliq;
    @XmlElement(required = true)
    protected String pAliqEfet;

    /**
     * Gets the value of the pRedAliq property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPRedAliq() {
        return pRedAliq;
    }

    /**
     * Sets the value of the pRedAliq property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPRedAliq(String value) {
        this.pRedAliq = value;
    }

    public boolean isSetPRedAliq() {
        return (this.pRedAliq != null);
    }

    /**
     * Gets the value of the pAliqEfet property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPAliqEfet() {
        return pAliqEfet;
    }

    /**
     * Sets the value of the pAliqEfet property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPAliqEfet(String value) {
        this.pAliqEfet = value;
    }

    public boolean isSetPAliqEfet() {
        return (this.pAliqEfet != null);
    }

}
