# DATASOURCE
spring.datasource.url=jdbc:${DB_VENDOR:mysql}://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:dfe}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=true

# LOGGING
logging.level.web=${LOGGING_WEB:DEBUG}

# API DOCS
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs

# JACKSON
spring.jackson.mapper.accept-case-insensitive-values=true
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.mapper.accept-case-insensitive-properties=true

# DFE KEYSTORE
dfe.keystore.default-uf=${DEFAULT_KEYSTORE_UF:22}
dfe.keystore.default-cnpj=${DEFAULT_KEYSTORE_CNPJ:11520224000140}
dfe.keystore.default-environment=${DEFAULT_KEYSTORE_ENVIROMENT:2}

# JWT CONFIG
dfe.jwt.auth.secret=${JWT_SECRET:wl)v^ulwlx3!b@9c6^k4dfsv9@)30he^eb7+@u#jh)3xgujg5#}
dfe.jwt.auth.expiration-ms=86400000
