//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.11 at 12:19:31 PM BRT 
//


package br.inf.portalfiscal.nfe.event_generic;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.dfe.interfaces.xml.generic.XML;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="descEvento"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Perecimento, perda, roubo ou furto durante o transporte contratado pelo fornecedor"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cOrgaoAutor" type="{http://www.portalfiscal.inf.br/nfe}TCodUfIBGE"/&gt;
 *         &lt;element name="tpAutor"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="verAplic" type="{http://www.portalfiscal.inf.br/nfe}TVerAplic"/&gt;
 *         &lt;element name="gPerecimento" maxOccurs="990"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="vIBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
 *                   &lt;element name="vCBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
 *                   &lt;element name="gControleEstoque"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="qPerecimento" type="{http://www.portalfiscal.inf.br/nfe}TDec_1104"/&gt;
 *                             &lt;element name="uPerecimento"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
 *                                   &lt;maxLength value="6"/&gt;
 *                                   &lt;minLength value="1"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="vIBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
 *                               &lt;element name="vCBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="nItem" use="required" type="{http://www.portalfiscal.inf.br/nfe}TnItem" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="versao"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;whiteSpace value="preserve"/&gt;
 *             &lt;enumeration value="1.00"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descEvento",
    "cOrgaoAutor",
    "tpAutor",
    "verAplic",
    "gPerecimento"
})
@XmlRootElement(name = "detEventoPercPerdRouboFornecedor")
public class DetEventoPercPerdRouboFornecedor
    implements XML
{

    @XmlElement(required = true)
    protected String descEvento;
    @XmlElement(required = true)
    protected String cOrgaoAutor;
    @XmlElement(required = true)
    protected String tpAutor;
    @XmlElement(required = true)
    protected String verAplic;
    @XmlElement(required = true)
    protected List<GPerecimento> gPerecimento;
    @XmlAttribute(name = "versao")
    protected String versao;

    /**
     * Gets the value of the descEvento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescEvento() {
        return descEvento;
    }

    /**
     * Sets the value of the descEvento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescEvento(String value) {
        this.descEvento = value;
    }

    public boolean isSetDescEvento() {
        return (this.descEvento!= null);
    }

    /**
     * Gets the value of the cOrgaoAutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOrgaoAutor() {
        return cOrgaoAutor;
    }

    /**
     * Sets the value of the cOrgaoAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOrgaoAutor(String value) {
        this.cOrgaoAutor = value;
    }

    public boolean isSetCOrgaoAutor() {
        return (this.cOrgaoAutor!= null);
    }

    /**
     * Gets the value of the tpAutor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpAutor() {
        return tpAutor;
    }

    /**
     * Sets the value of the tpAutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpAutor(String value) {
        this.tpAutor = value;
    }

    public boolean isSetTpAutor() {
        return (this.tpAutor!= null);
    }

    /**
     * Gets the value of the verAplic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerAplic() {
        return verAplic;
    }

    /**
     * Sets the value of the verAplic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerAplic(String value) {
        this.verAplic = value;
    }

    public boolean isSetVerAplic() {
        return (this.verAplic!= null);
    }

    /**
     * Gets the value of the gPerecimento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the gPerecimento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGPerecimento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GPerecimento }
     * 
     * 
     */
    public List<GPerecimento> getGPerecimento() {
        if (gPerecimento == null) {
            gPerecimento = new ArrayList<GPerecimento>();
        }
        return this.gPerecimento;
    }

    public boolean isSetGPerecimento() {
        return ((this.gPerecimento!= null)&&(!this.gPerecimento.isEmpty()));
    }

    public void unsetGPerecimento() {
        this.gPerecimento = null;
    }

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersao(String value) {
        this.versao = value;
    }

    public boolean isSetVersao() {
        return (this.versao!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="vIBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
     *         &lt;element name="vCBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
     *         &lt;element name="gControleEstoque"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="qPerecimento" type="{http://www.portalfiscal.inf.br/nfe}TDec_1104"/&gt;
     *                   &lt;element name="uPerecimento"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
     *                         &lt;maxLength value="6"/&gt;
     *                         &lt;minLength value="1"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="vIBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
     *                     &lt;element name="vCBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="nItem" use="required" type="{http://www.portalfiscal.inf.br/nfe}TnItem" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vibs",
        "vcbs",
        "gControleEstoque"
    })
    public static class GPerecimento
        implements XML
    {

        @XmlElement(name = "vIBS", required = true)
        protected String vibs;
        @XmlElement(name = "vCBS", required = true)
        protected String vcbs;
        @XmlElement(required = true)
        protected GControleEstoque gControleEstoque;
        @XmlAttribute(name = "nItem", required = true)
        protected String nItem;

        /**
         * Gets the value of the vibs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVIBS() {
            return vibs;
        }

        /**
         * Sets the value of the vibs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVIBS(String value) {
            this.vibs = value;
        }

        public boolean isSetVIBS() {
            return (this.vibs!= null);
        }

        /**
         * Gets the value of the vcbs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVCBS() {
            return vcbs;
        }

        /**
         * Sets the value of the vcbs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVCBS(String value) {
            this.vcbs = value;
        }

        public boolean isSetVCBS() {
            return (this.vcbs!= null);
        }

        /**
         * Gets the value of the gControleEstoque property.
         * 
         * @return
         *     possible object is
         *     {@link GControleEstoque }
         *     
         */
        public GControleEstoque getGControleEstoque() {
            return gControleEstoque;
        }

        /**
         * Sets the value of the gControleEstoque property.
         * 
         * @param value
         *     allowed object is
         *     {@link GControleEstoque }
         *     
         */
        public void setGControleEstoque(GControleEstoque value) {
            this.gControleEstoque = value;
        }

        public boolean isSetGControleEstoque() {
            return (this.gControleEstoque!= null);
        }

        /**
         * Gets the value of the nItem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNItem() {
            return nItem;
        }

        /**
         * Sets the value of the nItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNItem(String value) {
            this.nItem = value;
        }

        public boolean isSetNItem() {
            return (this.nItem!= null);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="qPerecimento" type="{http://www.portalfiscal.inf.br/nfe}TDec_1104"/&gt;
         *         &lt;element name="uPerecimento"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString"&gt;
         *               &lt;maxLength value="6"/&gt;
         *               &lt;minLength value="1"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="vIBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
         *           &lt;element name="vCBS" type="{http://www.portalfiscal.inf.br/nfe}TDec_1302"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "qPerecimento",
            "uPerecimento",
            "vibs",
            "vcbs"
        })
        public static class GControleEstoque
            implements XML
        {

            @XmlElement(required = true)
            protected String qPerecimento;
            @XmlElement(required = true)
            protected String uPerecimento;
            @XmlElement(name = "vIBS", required = true)
            protected String vibs;
            @XmlElement(name = "vCBS", required = true)
            protected String vcbs;

            /**
             * Gets the value of the qPerecimento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQPerecimento() {
                return qPerecimento;
            }

            /**
             * Sets the value of the qPerecimento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQPerecimento(String value) {
                this.qPerecimento = value;
            }

            public boolean isSetQPerecimento() {
                return (this.qPerecimento!= null);
            }

            /**
             * Gets the value of the uPerecimento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUPerecimento() {
                return uPerecimento;
            }

            /**
             * Sets the value of the uPerecimento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUPerecimento(String value) {
                this.uPerecimento = value;
            }

            public boolean isSetUPerecimento() {
                return (this.uPerecimento!= null);
            }

            /**
             * Gets the value of the vibs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVIBS() {
                return vibs;
            }

            /**
             * Sets the value of the vibs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVIBS(String value) {
                this.vibs = value;
            }

            public boolean isSetVIBS() {
                return (this.vibs!= null);
            }

            /**
             * Gets the value of the vcbs property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVCBS() {
                return vcbs;
            }

            /**
             * Sets the value of the vcbs property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVCBS(String value) {
                this.vcbs = value;
            }

            public boolean isSetVCBS() {
                return (this.vcbs!= null);
            }

        }

    }

}
