//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.11 at 12:19:31 PM BRT 
//


package br.inf.portalfiscal.nfe.event_generic;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.nfe.event_generic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    public final static QName _EnvEvento_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "envEvento");
    public final static QName _ProcEventoNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "procEventoNFe");
    public final static QName _RetEnvEvento_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retEnvEvento");
    public final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.nfe.event_generic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DetEventoEPEC }
     * 
     */
    public DetEventoEPEC createDetEventoEPEC() {
        return new DetEventoEPEC();
    }

    /**
     * Create an instance of {@link DetEventoAtorInteressado }
     * 
     */
    public DetEventoAtorInteressado createDetEventoAtorInteressado() {
        return new DetEventoAtorInteressado();
    }

    /**
     * Create an instance of {@link DetEventoImpALCZFM }
     * 
     */
    public DetEventoImpALCZFM createDetEventoImpALCZFM() {
        return new DetEventoImpALCZFM();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboFornecedor }
     * 
     */
    public DetEventoPercPerdRouboFornecedor createDetEventoPercPerdRouboFornecedor() {
        return new DetEventoPercPerdRouboFornecedor();
    }

    /**
     * Create an instance of {@link DetEventoFornecimentoNaoRealizado }
     * 
     */
    public DetEventoFornecimentoNaoRealizado createDetEventoFornecimentoNaoRealizado() {
        return new DetEventoFornecimentoNaoRealizado();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCred }
     * 
     */
    public DetEventoSolicApropCred createDetEventoSolicApropCred() {
        return new DetEventoSolicApropCred();
    }

    /**
     * Create an instance of {@link DetEventoUsoConsumo }
     * 
     */
    public DetEventoUsoConsumo createDetEventoUsoConsumo() {
        return new DetEventoUsoConsumo();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboAdquirente }
     * 
     */
    public DetEventoPercPerdRouboAdquirente createDetEventoPercPerdRouboAdquirente() {
        return new DetEventoPercPerdRouboAdquirente();
    }

    /**
     * Create an instance of {@link DetEventoImobilizacaoItem }
     * 
     */
    public DetEventoImobilizacaoItem createDetEventoImobilizacaoItem() {
        return new DetEventoImobilizacaoItem();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCredComb }
     * 
     */
    public DetEventoSolicApropCredComb createDetEventoSolicApropCredComb() {
        return new DetEventoSolicApropCredComb();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCredBensServDepAtivAdq }
     * 
     */
    public DetEventoSolicApropCredBensServDepAtivAdq createDetEventoSolicApropCredBensServDepAtivAdq() {
        return new DetEventoSolicApropCredBensServDepAtivAdq();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link TRetEvento }
     * 
     */
    public TRetEvento createTRetEvento() {
        return new TRetEvento();
    }

    /**
     * Create an instance of {@link TEvento }
     * 
     */
    public TEvento createTEvento() {
        return new TEvento();
    }

    /**
     * Create an instance of {@link TEvento.InfEvento }
     * 
     */
    public TEvento.InfEvento createTEventoInfEvento() {
        return new TEvento.InfEvento();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCredComb.GConsumoComb }
     * 
     */
    public DetEventoSolicApropCredComb.GConsumoComb createDetEventoSolicApropCredCombGConsumoComb() {
        return new DetEventoSolicApropCredComb.GConsumoComb();
    }

    /**
     * Create an instance of {@link DetEventoImobilizacaoItem.GImobilizacao }
     * 
     */
    public DetEventoImobilizacaoItem.GImobilizacao createDetEventoImobilizacaoItemGImobilizacao() {
        return new DetEventoImobilizacaoItem.GImobilizacao();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboAdquirente.GPerecimento }
     * 
     */
    public DetEventoPercPerdRouboAdquirente.GPerecimento createDetEventoPercPerdRouboAdquirenteGPerecimento() {
        return new DetEventoPercPerdRouboAdquirente.GPerecimento();
    }

    /**
     * Create an instance of {@link DetEventoUsoConsumo.GConsumo }
     * 
     */
    public DetEventoUsoConsumo.GConsumo createDetEventoUsoConsumoGConsumo() {
        return new DetEventoUsoConsumo.GConsumo();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCred.GCredPres }
     * 
     */
    public DetEventoSolicApropCred.GCredPres createDetEventoSolicApropCredGCredPres() {
        return new DetEventoSolicApropCred.GCredPres();
    }

    /**
     * Create an instance of {@link DetEventoFornecimentoNaoRealizado.GItemNaoFornecido }
     * 
     */
    public DetEventoFornecimentoNaoRealizado.GItemNaoFornecido createDetEventoFornecimentoNaoRealizadoGItemNaoFornecido() {
        return new DetEventoFornecimentoNaoRealizado.GItemNaoFornecido();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboFornecedor.GPerecimento }
     * 
     */
    public DetEventoPercPerdRouboFornecedor.GPerecimento createDetEventoPercPerdRouboFornecedorGPerecimento() {
        return new DetEventoPercPerdRouboFornecedor.GPerecimento();
    }

    /**
     * Create an instance of {@link DetEventoImpALCZFM.GConsumo }
     * 
     */
    public DetEventoImpALCZFM.GConsumo createDetEventoImpALCZFMGConsumo() {
        return new DetEventoImpALCZFM.GConsumo();
    }

    /**
     * Create an instance of {@link DetEventoCancEv }
     * 
     */
    public DetEventoCancEv createDetEventoCancEv() {
        return new DetEventoCancEv();
    }

    /**
     * Create an instance of {@link DetEventoCCe }
     * 
     */
    public DetEventoCCe createDetEventoCCe() {
        return new DetEventoCCe();
    }

    /**
     * Create an instance of {@link DetEventoCanc }
     * 
     */
    public DetEventoCanc createDetEventoCanc() {
        return new DetEventoCanc();
    }

    /**
     * Create an instance of {@link DetEventoCancSubs }
     * 
     */
    public DetEventoCancSubs createDetEventoCancSubs() {
        return new DetEventoCancSubs();
    }

    /**
     * Create an instance of {@link DetEventoCompEntreg }
     * 
     */
    public DetEventoCompEntreg createDetEventoCompEntreg() {
        return new DetEventoCompEntreg();
    }

    /**
     * Create an instance of {@link DetEventoEPEC.Dest }
     * 
     */
    public DetEventoEPEC.Dest createDetEventoEPECDest() {
        return new DetEventoEPEC.Dest();
    }

    /**
     * Create an instance of {@link DetEventoAtorInteressado.AutXML }
     * 
     */
    public DetEventoAtorInteressado.AutXML createDetEventoAtorInteressadoAutXML() {
        return new DetEventoAtorInteressado.AutXML();
    }

    /**
     * Create an instance of {@link DetEventoPagIntegral }
     * 
     */
    public DetEventoPagIntegral createDetEventoPagIntegral() {
        return new DetEventoPagIntegral();
    }

    /**
     * Create an instance of {@link DetEventoManifestacao }
     * 
     */
    public DetEventoManifestacao createDetEventoManifestacao() {
        return new DetEventoManifestacao();
    }

    /**
     * Create an instance of {@link DetEventoAceiteDebito }
     * 
     */
    public DetEventoAceiteDebito createDetEventoAceiteDebito() {
        return new DetEventoAceiteDebito();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCredBensServDepAtivAdq.GCredito }
     * 
     */
    public DetEventoSolicApropCredBensServDepAtivAdq.GCredito createDetEventoSolicApropCredBensServDepAtivAdqGCredito() {
        return new DetEventoSolicApropCredBensServDepAtivAdq.GCredito();
    }

    /**
     * Create an instance of {@link DetEventoManifestacaoPedTransfCredIBS }
     * 
     */
    public DetEventoManifestacaoPedTransfCredIBS createDetEventoManifestacaoPedTransfCredIBS() {
        return new DetEventoManifestacaoPedTransfCredIBS();
    }

    /**
     * Create an instance of {@link DetEventoManifestacaoPedTransfCredCBS }
     * 
     */
    public DetEventoManifestacaoPedTransfCredCBS createDetEventoManifestacaoPedTransfCredCBS() {
        return new DetEventoManifestacaoPedTransfCredCBS();
    }

    /**
     * Create an instance of {@link DetEventoManifestacaoFiscoPedTransfCredIBS }
     * 
     */
    public DetEventoManifestacaoFiscoPedTransfCredIBS createDetEventoManifestacaoFiscoPedTransfCredIBS() {
        return new DetEventoManifestacaoFiscoPedTransfCredIBS();
    }

    /**
     * Create an instance of {@link DetEventoManifestacaoFiscoPedTransfCredCBS }
     * 
     */
    public DetEventoManifestacaoFiscoPedTransfCredCBS createDetEventoManifestacaoFiscoPedTransfCredCBS() {
        return new DetEventoManifestacaoFiscoPedTransfCredCBS();
    }

    /**
     * Create an instance of {@link TEnvEvento }
     * 
     */
    public TEnvEvento createTEnvEvento() {
        return new TEnvEvento();
    }

    /**
     * Create an instance of {@link TProcEvento }
     * 
     */
    public TProcEvento createTProcEvento() {
        return new TProcEvento();
    }

    /**
     * Create an instance of {@link TRetEnvEvento }
     * 
     */
    public TRetEnvEvento createTRetEnvEvento() {
        return new TRetEnvEvento();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignatureValueType }
     * 
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link ReferenceType.DigestMethod }
     * 
     */
    public ReferenceType.DigestMethod createReferenceTypeDigestMethod() {
        return new ReferenceType.DigestMethod();
    }

    /**
     * Create an instance of {@link SignedInfoType.CanonicalizationMethod }
     * 
     */
    public SignedInfoType.CanonicalizationMethod createSignedInfoTypeCanonicalizationMethod() {
        return new SignedInfoType.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link SignedInfoType.SignatureMethod }
     * 
     */
    public SignedInfoType.SignatureMethod createSignedInfoTypeSignatureMethod() {
        return new SignedInfoType.SignatureMethod();
    }

    /**
     * Create an instance of {@link TRetEvento.InfEvento }
     * 
     */
    public TRetEvento.InfEvento createTRetEventoInfEvento() {
        return new TRetEvento.InfEvento();
    }

    /**
     * Create an instance of {@link TEvento.InfEvento.DetEvento }
     * 
     */
    public TEvento.InfEvento.DetEvento createTEventoInfEventoDetEvento() {
        return new TEvento.InfEvento.DetEvento();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCredComb.GConsumoComb.GControleEstoque }
     * 
     */
    public DetEventoSolicApropCredComb.GConsumoComb.GControleEstoque createDetEventoSolicApropCredCombGConsumoCombGControleEstoque() {
        return new DetEventoSolicApropCredComb.GConsumoComb.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoImobilizacaoItem.GImobilizacao.GControleEstoque }
     * 
     */
    public DetEventoImobilizacaoItem.GImobilizacao.GControleEstoque createDetEventoImobilizacaoItemGImobilizacaoGControleEstoque() {
        return new DetEventoImobilizacaoItem.GImobilizacao.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboAdquirente.GPerecimento.GControleEstoque }
     * 
     */
    public DetEventoPercPerdRouboAdquirente.GPerecimento.GControleEstoque createDetEventoPercPerdRouboAdquirenteGPerecimentoGControleEstoque() {
        return new DetEventoPercPerdRouboAdquirente.GPerecimento.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoUsoConsumo.GConsumo.GControleEstoque }
     * 
     */
    public DetEventoUsoConsumo.GConsumo.GControleEstoque createDetEventoUsoConsumoGConsumoGControleEstoque() {
        return new DetEventoUsoConsumo.GConsumo.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoUsoConsumo.GConsumo.DFeReferenciado }
     * 
     */
    public DetEventoUsoConsumo.GConsumo.DFeReferenciado createDetEventoUsoConsumoGConsumoDFeReferenciado() {
        return new DetEventoUsoConsumo.GConsumo.DFeReferenciado();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCred.GCredPres.GIBS }
     * 
     */
    public DetEventoSolicApropCred.GCredPres.GIBS createDetEventoSolicApropCredGCredPresGIBS() {
        return new DetEventoSolicApropCred.GCredPres.GIBS();
    }

    /**
     * Create an instance of {@link DetEventoSolicApropCred.GCredPres.GCBS }
     * 
     */
    public DetEventoSolicApropCred.GCredPres.GCBS createDetEventoSolicApropCredGCredPresGCBS() {
        return new DetEventoSolicApropCred.GCredPres.GCBS();
    }

    /**
     * Create an instance of {@link DetEventoFornecimentoNaoRealizado.GItemNaoFornecido.GControleEstoque }
     * 
     */
    public DetEventoFornecimentoNaoRealizado.GItemNaoFornecido.GControleEstoque createDetEventoFornecimentoNaoRealizadoGItemNaoFornecidoGControleEstoque() {
        return new DetEventoFornecimentoNaoRealizado.GItemNaoFornecido.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoPercPerdRouboFornecedor.GPerecimento.GControleEstoque }
     * 
     */
    public DetEventoPercPerdRouboFornecedor.GPerecimento.GControleEstoque createDetEventoPercPerdRouboFornecedorGPerecimentoGControleEstoque() {
        return new DetEventoPercPerdRouboFornecedor.GPerecimento.GControleEstoque();
    }

    /**
     * Create an instance of {@link DetEventoImpALCZFM.GConsumo.GControleEstoque }
     * 
     */
    public DetEventoImpALCZFM.GConsumo.GControleEstoque createDetEventoImpALCZFMGConsumoGControleEstoque() {
        return new DetEventoImpALCZFM.GConsumo.GControleEstoque();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEnvEvento }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TEnvEvento }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "envEvento")
    public JAXBElement<TEnvEvento> createEnvEvento(TEnvEvento value) {
        return new JAXBElement<TEnvEvento>(_EnvEvento_QNAME, TEnvEvento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcEvento }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TProcEvento }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "procEventoNFe")
    public JAXBElement<TProcEvento> createProcEventoNFe(TProcEvento value) {
        return new JAXBElement<TProcEvento>(_ProcEventoNFe_QNAME, TProcEvento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetEnvEvento }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRetEnvEvento }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retEnvEvento")
    public JAXBElement<TRetEnvEvento> createRetEnvEvento(TRetEnvEvento value) {
        return new JAXBElement<TRetEnvEvento>(_RetEnvEvento_QNAME, TRetEnvEvento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

}
