package br.inf.portalfiscal.cte.wsdl.query_situation.ms.hom;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 */
@WebService(name = "CteConsultaSoap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.cte.send.ObjectFactory.class
})
public interface CteConsultaSoap12 {


    /**
     * @param cteCabecMsg
     * @param cteDadosMsg
     * @return returns br.inf.portalfiscal.cte.wsdl.query_situation.ms.hom.CteConsultaCTResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/cteConsultaCT")
    @WebResult(name = "cteConsultaCTResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", partName = "cteConsultaCTResult")
    @Action(input = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/cteConsultaCT", output = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/CteConsultaSoap12/cteConsultaCTResponse")
    public CteConsultaCTResult cteConsultaCT(
            @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", partName = "cteDadosMsg")
            CteDadosMsg cteDadosMsg,
            @WebParam(name = "cteCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", header = true, mode = WebParam.Mode.INOUT, partName = "cteCabecMsg")
            Holder<CTeCabecMsg> cteCabecMsg);

}
