package br.inf.portalfiscal.nfe.wsdl.query_register.mg.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.Response;

import java.util.concurrent.Future;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 *
 */
@WebService(name = "CadConsultaCadastro4Soap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class, br.inf.portalfiscal.nfe.send.ObjectFactory.class
})
public interface CadConsultaCadastro4Soap {


    /**
     *
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return returns jakarta.xml.ws.Response<br.inf.portalfiscal.nfe.wsdl.query_register.mg.prod.ConsultaCadastroResponse>
     */
    @WebMethod(operationName = "consultaCadastro", action = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro")
    public Response<ConsultaCadastroResponse> consultaCadastroAsync(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", header = true, partName = "nfeCabecMsg")
            NfeCabecMsg nfeCabecMsg);

    /**
     *
     * @param asyncHandler
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "consultaCadastro", action = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro")
    public Future<?> consultaCadastroAsync(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", header = true, partName = "nfeCabecMsg")
            NfeCabecMsg nfeCabecMsg,
            @WebParam(name = "consultaCadastroResponse", targetNamespace = "", partName = "asyncHandler")
            AsyncHandler<ConsultaCadastroResponse> asyncHandler);

    /**
     *
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return returns br.inf.portalfiscal.nfe.wsdl.query_register.mg.prod.ConsultaCadastro4Result
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro")
    @WebResult(name = "consultaCadastro4Result", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", partName = "consultaCadastro4Result")
    @Action(input = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", output = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/CadConsultaCadastro4Soap/consultaCadastroResponse")
    public ConsultaCadastro4Result consultaCadastro(
            @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", partName = "nfeDadosMsg")
            NfeDadosMsg nfeDadosMsg,
            @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", header = true, mode = WebParam.Mode.INOUT, partName = "nfeCabecMsg")
            Holder<NfeCabecMsg> nfeCabecMsg);

}
