//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:01:07 PM BRT 
//


package br.inf.portalfiscal.nfe.event_epec;

import com.softart.dfe.interfaces.xml.generic.XML;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for EpecDest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EpecDest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}UF"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/nfe}TCnpj"/&gt;
 *           &lt;element name="CPF" type="{http://www.portalfiscal.inf.br/nfe}TCpf"/&gt;
 *           &lt;element name="idEstrangeiro"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                 &lt;whiteSpace value="preserve"/&gt;
 *                 &lt;pattern value="([!-ÿ]{0}|[!-ÿ]{5,20})?"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}IE" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}vNF"/&gt;
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}vICMS"/&gt;
 *         &lt;element ref="{http://www.portalfiscal.inf.br/nfe}vST"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpecDest", propOrder = {
        "uf",
        "cnpj",
        "cpf",
        "idEstrangeiro",
        "ie",
        "vnf",
        "vicms",
        "vst"
})
public class EpecDest
        implements XML {

    @XmlElement(name = "UF", required = true)
    @XmlSchemaType(name = "string")
    protected TUf uf;
    @XmlElement(name = "CNPJ")
    protected String cnpj;
    @XmlElement(name = "CPF")
    protected String cpf;
    protected String idEstrangeiro;
    @XmlElement(name = "IE")
    protected String ie;
    @XmlElement(name = "vNF", required = true)
    protected String vnf;
    @XmlElement(name = "vICMS", required = true)
    protected String vicms;
    @XmlElement(name = "vST", required = true)
    protected String vst;

    /**
     * Gets the value of the uf property.
     *
     * @return possible object is
     * {@link TUf }
     */
    public TUf getUF() {
        return uf;
    }

    /**
     * Sets the value of the uf property.
     *
     * @param value allowed object is
     *              {@link TUf }
     */
    public void setUF(TUf value) {
        this.uf = value;
    }

    public boolean isSetUF() {
        return (this.uf != null);
    }

    /**
     * Gets the value of the cnpj property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCNPJ() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCNPJ(String value) {
        this.cnpj = value;
    }

    public boolean isSetCNPJ() {
        return (this.cnpj != null);
    }

    /**
     * Gets the value of the cpf property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCPF() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCPF(String value) {
        this.cpf = value;
    }

    public boolean isSetCPF() {
        return (this.cpf != null);
    }

    /**
     * Gets the value of the idEstrangeiro property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIdEstrangeiro() {
        return idEstrangeiro;
    }

    /**
     * Sets the value of the idEstrangeiro property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIdEstrangeiro(String value) {
        this.idEstrangeiro = value;
    }

    public boolean isSetIdEstrangeiro() {
        return (this.idEstrangeiro != null);
    }

    /**
     * Gets the value of the ie property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIE() {
        return ie;
    }

    /**
     * Sets the value of the ie property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIE(String value) {
        this.ie = value;
    }

    public boolean isSetIE() {
        return (this.ie != null);
    }

    /**
     * Gets the value of the vnf property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVNF() {
        return vnf;
    }

    /**
     * Sets the value of the vnf property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVNF(String value) {
        this.vnf = value;
    }

    public boolean isSetVNF() {
        return (this.vnf != null);
    }

    /**
     * Gets the value of the vicms property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVICMS() {
        return vicms;
    }

    /**
     * Sets the value of the vicms property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVICMS(String value) {
        this.vicms = value;
    }

    public boolean isSetVICMS() {
        return (this.vicms != null);
    }

    /**
     * Gets the value of the vst property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVST() {
        return vst;
    }

    /**
     * Sets the value of the vst property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVST(String value) {
        this.vst = value;
    }

    public boolean isSetVST() {
        return (this.vst != null);
    }

}
