package com.softart.dfe.enums.nf;

import com.softart.dfe.components.internal.DFEnum;
import com.softart.dfe.exceptions.NoEnumException;
import com.softart.dfe.interfaces.internal.ReturnCode;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.extern.log4j.Log4j2;

import java.util.Arrays;
import java.util.Collection;
import java.util.Optional;

@Getter
@AllArgsConstructor
@Log4j2
public enum NFReturnCode implements ReturnCode {
    CODE_100("100", "Autorizado o uso da NF-e"),
    CODE_101("101", "Cancelamento de NF-e homologado"),
    CODE_102("102", "Inutilização de número homologado"),
    CODE_103("103", "Lote recebido com sucesso"),
    CODE_104("104", "Lote processado"),
    CODE_105("105", "Lote em processamento"),
    CODE_106("106", "Lote não localizado"),
    CODE_107("107", "Serviço em Operação"),
    CODE_108("108", "Serviço Paralisado Momentaneamente (curto prazo)"),
    CODE_109("109", "Serviço Paralisado sem Previsão"),
    CODE_110("110", "Uso Denegado"),
    CODE_111("111", "Consulta cadastro com uma ocorrência"),
    CODE_112("112", "Consulta cadastro com mais de uma ocorrência"),
    CODE_124("124", "EPEC Autorizado"),
    CODE_128("128", "Lote de Evento Processado"),
    CODE_135("135", "Evento registrado e vinculado a NF-e"),
    CODE_136("136", "Evento registrado, mas não vinculado a NF-e"),
    CODE_137("137", "Nenhum documento localizado para o Destinatário"),
    CODE_138("138", "Documento localizado para o Destinatário"),
    CODE_139("139", "Pedido de Download processado"),
    CODE_140("140", "Download disponibilizado"),
    CODE_142("142", "Ambiente de Contingência EPEC bloqueado para o Emitente"),
    CODE_150("150", "Autorizado o uso da NF-e, autorização fora de prazo"),
    CODE_151("151", "Cancelamento de NF-e homologado fora de prazo"),

    CODE_301("301", "Uso Denegado: Irregularidade fiscal do emitente"),
    CODE_302("302", "Uso Denegado: Irregularidade fiscal do destinatário"),
    CODE_303("303", "Uso Denegado: Destinatário não habilitado a operar na UF"),

    CODE_201("201", "Rejeição: Número máximo de numeração a inutilizar ultrapassou o limite"),
    CODE_203("203", "Rejeição: Emissor não habilitado para emissão da NF-e"),
    CODE_204("204", "Rejeição: Duplicidade de NF-e [nRec:999999999999999]"),
    CODE_205("205", "Rejeição: NF-e está denegada na base de dados da SEFAZ [nRec:999999999999999]"),
    CODE_206("206", "Rejeição: NF-e já está inutilizada na Base de Dados da SEFAZ"),
    CODE_207("207", "Rejeição: CNPJ do emitente inválido"),
    CODE_208("208", "Rejeição: CNPJ do destinatário inválido"),
    CODE_209("209", "Rejeição: IE do emitente inválida"),
    CODE_210("210", "Rejeição: IE do destinatário inválida"),
    CODE_211("211", "Rejeição: IE do substituto inválida"),
    CODE_212("212", "Rejeição: Data de emissão NF-e posterior a data de recebimento"),
    CODE_213("213", "Rejeição: CNPJ-Base do Emitente difere do CNPJ-Base do Certificado Digital"),
    CODE_214("214", "Rejeição: Tamanho da mensagem excedeu o limite estabelecido"),
    CODE_215("215", "Rejeição: Falha no schema XML"),
    CODE_217("217", "Rejeição: NF-e não consta na base de dados da SEFAZ"),
    CODE_218("218", "Rejeição: NF-e já está cancelada na base de dados da SEFAZ [nRec:999999999999999]"),
    CODE_219("219", "Rejeição: Circulação da NF-e verificada"),
    CODE_220("220", "Rejeição: Destinatário com identificação igual à identificação do emitente"),
    CODE_221("221", "Rejeição: Confirmado o recebimento da NF-e pelo destinatário"),
    CODE_222("222", "Rejeição: Protocolo de Autorização de Uso difere do cadastrado"),
    CODE_223("223", "Rejeição: CNPJ/CPF do transmissor do lote difere do CNPJ/CPF do transmissor da consulta"),
    CODE_224("224", "Rejeição: A faixa inicial é maior que a faixa final"),
    CODE_225("225", "Rejeição: Falha no Schema XML do lote de NFe"),
    CODE_226("226", "Rejeição: Código da UF do Emitente diverge da UF autorizadora"),
    CODE_227("227", "Rejeição: CPF do Emitente difere do CPF do Certificado Digital"),
    CODE_228("228", "Rejeição: Data de Emissão muito atrasada"),
    CODE_229("229", "Rejeição: IE do emitente não informada"),
    CODE_230("230", "Rejeição: IE do emitente não cadastrada"),
    CODE_231("231", "Rejeição: IE do emitente não vinculada ao CNPJ"),
    CODE_232("232", "Rejeição: IE do destinatário não informada"),
    CODE_233("233", "Rejeição: IE do destinatário não cadastrada"),
    CODE_234("234", "Rejeição: IE do destinatário não vinculada ao CNPJ"),
    CODE_235("235", "Rejeição: Inscrição SUFRAMA inválida"),
    CODE_236("236", "Rejeição: Chave de Acesso com dígito verificador inválido"),
    CODE_237("237", "Rejeição: CPF do destinatário inválido"),
    CODE_239("239", "Rejeição: Versão do arquivo XML não suportada (NT 2108.004)"),
    CODE_240("240", "Rejeição: Irregularidade Fiscal do Emitente"),
    CODE_241("241", "Rejeição: Um número da faixa já foi utilizado"),
    CODE_243("243", "Rejeição: XML Mal Formado"),
    CODE_244("244", "Rejeição: Processo de Emissão pelo Contribuinte incompatível com a Série da NF"),
    CODE_245("245", "Rejeição: CNPJ Emitente não cadastrado"),
    CODE_246("246", "Rejeição: CNPJ Destinatário não cadastrado"),
    CODE_247("247", "Rejeição: Sigla da UF do Emitente diverge da UF autorizadora"),
    CODE_248("248", "Rejeição: UF do Recibo diverge da UF autorizadora"),
    CODE_249("249", "Rejeição: UF da Chave de Acesso diverge da UF autorizadora"),
    CODE_250("250", "Rejeição: UF diverge da UF autorizadora"),
    CODE_251("251", "Rejeição: UF/Município destinatário não pertence a SUFRAMA"),
    CODE_252("252", "Rejeição: Ambiente informado diverge do Ambiente de recebimento"),
    CODE_253("253", "Rejeição: Digito Verificador da chave de acesso composta inválida"),
    CODE_254("254", "Rejeição: NF-e complementar não possui NF referenciada"),
    CODE_255("255", "Rejeição: NF-e complementar possui mais de uma NF referenciada"),
    CODE_256("256", "Rejeição: Uma NF-e da faixa já está inutilizada na Base de dados da SEFAZ"),
    CODE_257("257", "Rejeição: Solicitante não habilitado para emissão da NF-e"),
    CODE_258("258", "Rejeição: CNPJ da consulta inválido"),
    CODE_259("259", "Rejeição: CNPJ da consulta não cadastrado como contribuinte na UF"),
    CODE_260("260", "Rejeição: IE da consulta inválida"),
    CODE_261("261", "Rejeição: IE da consulta não cadastrada como contribuinte na UF"),
    CODE_262("262", "Rejeição: UF não fornece consulta por CPF"),
    CODE_263("263", "Rejeição: CPF da consulta inválido"),
    CODE_264("264", "Rejeição: CPF da consulta não cadastrado como contribuinte na UF"),
    CODE_265("265", "Rejeição: Sigla da UF da consulta difere da UF do Web Service"),
    CODE_266("266", "Rejeição: Série utilizada não permitida no Web Service"),
    CODE_267("267", "Rejeição: Chave de Acesso referenciada inexistente [nRef: xxx]"),
    CODE_268("268", "Rejeição: NF Complementar referencia uma outra NF-e Complementar"),
    CODE_269("269", "Rejeição: CNPJ/CPF Emitente da NF Complementar difere do CNPJ/CPF da NF Referenciada"),
    CODE_270("270", "Rejeição: Código Município do Fato Gerador de ICMS inexistente"),
    CODE_271("271", "Rejeição: Código Município do Fato Gerador: difere da UF do emitente"),
    CODE_272("272", "Rejeição: Código Município do Emitente inexistente"),
    CODE_273("273", "Rejeição: Código Município do Emitente: difere da UF do emitente"),
    CODE_274("274", "Rejeição: Código Município do Destinatário inexistente"),
    CODE_275("275", "Rejeição: Código Município do Destinatário: difere da UF do Destinatário"),
    CODE_276("276", "Rejeição: Código Município do Local de Retirada inexistente"),
    CODE_277("277", "Rejeição: Código Município do Local de Retirada: difere da UF do Local de Retirada"),
    CODE_278("278", "Rejeição: Código Município do Local de Entrega inexistente"),
    CODE_279("279", "Rejeição: Código Município do Local de Entrega: difere da UF do Local de Entrega"),
    CODE_280("280", "Rejeição: Certificado Transmissor inválido"),
    CODE_281("281", "Rejeição: Certificado Transmissor Data Validade"),
    CODE_282("282", "Rejeição: Certificado Transmissor sem CNPJ/CPF"),
    CODE_283("283", "Rejeição: Certificado Transmissor - erro Cadeia de Certificação"),
    CODE_284("284", "Rejeição: Certificado Transmissor revogado"),
    CODE_285("285", "Rejeição: Certificado Transmissor difere ICP-Brasil"),
    CODE_286("286", "Rejeição: Certificado Transmissor erro no acesso a LCR"),
    CODE_287("287", "Rejeição: Código Município do Fato Gerador de ISSQN inexistente [nItem:nnn]"),
    CODE_288("288", "Rejeição: Código Município do Fato Gerador do Transporte inexistente"),
    CODE_289("289", "Rejeição: Código da UF informada diverge da UF solicitada"),
    CODE_290("290", "Rejeição: Certificado Assinatura inválido"),
    CODE_291("291", "Rejeição: Certificado Assinatura Data Validade"),
    CODE_292("292", "Rejeição: Certificado de Assinatura sem CNPJ/CPF"),
    CODE_293("293", "Rejeição: Certificado Assinatura - erro Cadeia de Certificação"),
    CODE_294("294", "Rejeição: Certificado Assinatura revogado"),
    CODE_295("295", "Rejeição: Certificado Assinatura difere ICP-Brasil"),
    CODE_296("296", "Rejeição: Certificado Assinatura erro no acesso a LCR"),
    CODE_297("297", "Rejeição: Assinatura difere do calculado"),
    CODE_298("298", "Rejeição: Assinatura difere do padrão do Sistema"),
    CODE_304("304", "Rejeição: Pedido de Cancelamento para NF-e com evento da Suframa"),
    CODE_305("305", "Rejeição: Destinatário bloqueado na UF [NT 2019.001]"),
    CODE_306("306", "Rejeição: IE do destinatário não está ativa na UF [NT 2019.001]"),
    CODE_315("315", "Rejeição: Data de Emissão anterior ao início da autorização de Nota Fiscal na UF"),
    CODE_316("316", "Rejeição: Chave de Acesso referenciada com a mesma Chave de Acesso da Nota Fiscal atual [nOcor:nnn]"),
    CODE_317("317", "Rejeição: NF modelo 1 referenciada com data de emissão inválida [nOcor:nnn]"),
    CODE_318("318", "Rejeição: Contranota de Produtor sem Nota Fiscal referenciada"),
    CODE_319("319", "Rejeição: Contranota de Produtor não pode referenciar somente Nota Fiscal de entrada"),
    CODE_320("320", "Rejeição: Contranota de Produtor referencia somente NF de outro emitente"),
    CODE_321("321", "Rejeição: NF-e de devolução de mercadoria não possui documento fiscal referenciado"),
    CODE_322("322", "Rejeição: NF de produtor referenciada com data de emissão inválida [nOcor:nnn]"),
    CODE_323("323", "Rejeição: CNPJ autorizado para download inválido"),
    CODE_324("324", "Rejeição: CNPJ do destinatário já autorizado para download"),
    CODE_325("325", "Rejeição: CPF autorizado para download inválido"),
    CODE_326("326", "Rejeição: CPF do destinatário já autorizado para download"),
    CODE_327("327", "Rejeição: CFOP inválido para Nota Fiscal com finalidade de devolução de mercadoria[nItem:nnn]"),
    CODE_328("328", "Rejeição: CFOP de devolução de mercadoria para NF-e que não tem finalidade de devolução de mercadoria [nItem:nnn]"),
    CODE_329("329", "Rejeição: Número da DI /DSI inválido"),
    CODE_330("330", "Rejeição: Informar o Valor da AFRMM na importação por via marítima"),
    CODE_331("331", "Rejeição: Informar o CNPJ do adquirente ou do encomendante nesta forma de importação"),
    CODE_332("332", "Rejeição: CNPJ do adquirente ou do encomendante da importação inválido"),
    CODE_333("333", "Rejeição: Informar a UF do adquirente ou do encomendante nesta forma de importação"),
    CODE_334("334", "Rejeição: Número do processo de drawback não informado na importação"),
    CODE_335("335", "Rejeição: Número do processo de drawback na importação inválido"),
    CODE_336("336", "Rejeição: Informado o grupo de exportação no item em operação que não é com exterior [nItem: nnn]"),
    CODE_337("337", "Rejeição: NFC-e para emitente pessoa física"),
    CODE_338("338", "Rejeição: Número do processo de drawback não informado na exportação"),
    CODE_339("339", "Rejeição: Número do processo de drawback na exportação inválido"),
    CODE_340("340", "Rejeição: Não informado o grupo de exportação indireta no item"),
    CODE_341("341", "Rejeição: Número do registro de exportação inválido"),
    CODE_342("342", "Rejeição: Chave de Acesso informada na Exportação Indireta com DV inválido"),
    CODE_343("343", "Rejeição: Modelo da NF-e informada na Exportação Indireta diferente de 55"),
    CODE_344("344", "Rejeição: Duplicidade de NF-e informada na Exportação Indireta (Chave de Acesso informada mais de uma vez)"),
    CODE_345("345", "Rejeição: Chave de Acesso informada na Exportação Indireta não consta como NF-e referenciada"),
    CODE_346("346", "Rejeição: Somatório das quantidades informadas na Exportação Indireta não corresponde a quantidade total do item"),
    CODE_347("347", "Rejeição: Informada IE do substituto tributário em operação que não é interestadual"),
    CODE_348("348", "Rejeição: NFC-e com grupo RECOPI"),
    CODE_349("349", "Rejeição: Número RECOPI não informado"),
    CODE_350("350", "Rejeição: Número RECOPI inválido"),
    CODE_351("351", "Rejeição: Valor do ICMS da Operação no CST=51 difere do produto BC e Alíquota [nItem: 999]"),
    CODE_352("352", "Rejeição: Valor do ICMS Diferido no CST=51 difere do produto Valor ICMS Operação e percentual diferimento [nItem: 999]"),
    CODE_353("353", "Rejeição: Valor do ICMS no CST=51 não corresponde a diferença do ICMS operação e ICMS diferido [nItem: 999]"),
    CODE_354("354", "Rejeição: Informado grupo de devolução de tributos para NF-e que não tem finalidade de devolução de mercadoria"),
    CODE_355("355", "Rejeição: Informar o local de saída do Pais no caso da exportação"),
    CODE_356("356", "Rejeição: Informar o local de saída do Pais somente no caso da exportação"),
    CODE_357("357", "Rejeição: Chave de Acesso do grupo de Exportação Indireta inexistente [nRef: xxx]"),
    CODE_358("358", "Rejeição: Chave de Acesso do grupo de Exportação Indireta cancelada ou denegada [nRef: xxx ]"),
    CODE_359("359", "Rejeição: NF-e de venda a Órgão Público sem informar a Nota de Empenho"),
    CODE_360("360", "Rejeição: NF-e com Nota de Empenho inválida para a UF."),
    CODE_361("361", "Rejeição: NF-e com Nota de Empenho inexistente na UF."),
    CODE_362("362", "Rejeição: Venda de combustível sem informação do Transportador"),
    CODE_363("363", "Rejeição: IE do substituto tributário idêntica à IE do emitente ou do destinatário"),
    CODE_364("364", "Rejeição: Total do valor da dedução do ISS difere do somatório dos itens"),
    CODE_365("365", "Rejeição: Total de outras retenções difere do somatório dos itens"),
    CODE_366("366", "Rejeição: Total do desconto incondicionado ISS difere do somatório dos itens"),
    CODE_367("367", "Rejeição: Total do desconto condicionado ISS difere do somatório dos itens"),
    CODE_368("368", "Rejeição: Total de ISS retido difere do somatório dos itens"),
    CODE_369("369", "Rejeição: Não informado o grupo avulsa na emissão pelo Fisco"),
    CODE_370("370", "Rejeição: Processo de emissão pelo Fisco com Tipo de Emissão inválido"),
    CODE_372("372", "Rejeição: Destinatário com identificação de estrangeiro com caracteres inválidos"),
    CODE_373("373", "Rejeição: Descrição do primeiro item diferente de NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL [nItem:nnn]"),
    CODE_374("374", "Rejeição: CFOP incompatível com o grupo de tributação [nItem: nnn]"),
    CODE_375("375", "Rejeição: NF-e com lançamento relativo a Cupom Fiscal referencia uma NFC-e [nItem: nnn]"),
    CODE_376("376", "Rejeição: Data do Desembaraço Aduaneiro inválida [nItem: nnn]"),
    CODE_377("377", "Rejeição: Código de País do destinatário inexistente"),
    CODE_378("378", "Rejeição: Grupo de Combustível sem a informação de Encerrante [nItem: nnn]"),
    CODE_379("379", "Rejeição: Grupo de Encerrante na NF-e (modelo 55) para CFOP diferente de venda de combustível para consumidor final [nItem:nnn]"),
    CODE_380("380", "Rejeição: Valor do Encerrante final não é superior ao Encerrante inicial [nItem: nnn]"),
    CODE_381("381", "Rejeição: Grupo de tributação ICMS90, informando dados do ICMS-ST [nItem:nnn]"),
    CODE_382("382", "Rejeição: CFOP não permitido para o CST informado [nItem:nnn]"),
    CODE_383("383", "Rejeição: Item com CSOSN indevido [nItem: nnn]"),
    CODE_384("384", "Rejeição: CSOSN não permitido para a UF [nItem: nnn]"),
    CODE_385("385", "Rejeição: Grupo de tributação ICMSSN900, informando dados do ICMS-ST [nItem: nnn]"),
    CODE_386("386", "Rejeição: CFOP não permitido para o CSOSN informado [nItem: nnn]"),
    CODE_387("387", "Rejeição: Código de Enquadramento Legal do IPI inválido [nItem: nnn]"),
    CODE_388("388", "Rejeição: Código de Situação Tributária do IPI incompatível com o Código de Enquadramento Legal do IPI [nItem: nnn]"),
    CODE_389("389", "Rejeição: Código Município ISSQN inexistente [nItem:nnn]"),
    CODE_390("390", "Rejeição: Nota Fiscal com grupo de devolução de Tributos [nItem: nnn]"),
    CODE_391("391", "Rejeição: Não informados os dados do cartão de crédito / débito nas Formas de Pagamento da Nota Fiscal"),
    CODE_392("392", "Rejeição: Não informados os dados da operação de pagamento por cartão de crédito / débito"),
    CODE_393("393", "Rejeição: NF-e com o grupo de Informações Suplementares"),
    CODE_394("394", "Rejeição: Nota Fiscal sem a informação do QR-Code"),
    CODE_395("395", "Rejeição: Endereço do site da UF da Consulta via QR-Code diverge do previsto"),
    CODE_396("396", "Rejeição: Parâmetro do QR-Code inexistente: [Nome do parâmetro do QR Code: xxx)]"),
    CODE_397("397", "Rejeição: Parâmetro do QR-Code divergente da Nota Fiscal: [Nome do parâmetro do QR Code:: xxx)]"),
    CODE_398("398", "Rejeição: Parâmetro Versão informada no QR-Code diverge do previsto (“2”)"),
    CODE_399("399", "Rejeição: Parâmetro de Identificação do destinatário no QR-Code para Nota Fiscal sem identificação do destinatário"),
    CODE_400("400", "Rejeição: Parâmetro do QR-Code não está no formato hexadecimal: [Nome do parâmetro do QR Code: xxx)]"),
    CODE_401("401", "Rejeição: CPF do emitente inválido"),
    CODE_402("402", "Rejeição: XML da área de dados com codificação diferente de UTF-8"),
    CODE_403("403", "Rejeição: O grupo de informações da NF-e avulsa é de uso exclusivo do Fisco"),
    CODE_404("404", "Rejeição: Uso de prefixo de namespace não permitido"),
    CODE_407("407", "Rejeição: CPF do Emitente somente no serviço de Nota Fiscal Avulsa no site do Fisco"),
    CODE_408("408", "Rejeição: Evento não disponível para Autor pessoa física"),
    CODE_410("410", "Rejeição: UF informada no campo cUF não é atendida pelo WebService (NT 2018.004)"),
    CODE_417("417", "Rejeição: Total do ICMS superior ao valor limite estabelecido"),
    CODE_418("418", "Rejeição: Total do ICMS ST superior ao valor limite estabelecido"),
    CODE_434("434", "Rejeição: NF-e sem indicativo do intermediador (NT 2020.006)"),
    CODE_435("435", "Rejeição: NF-e não pode ter o indicativo do intermediador (NT 2020.006)"),
    CODE_436("436", "Rejeição: Informado 99-Outros como meio de pagamento (NT 2020.006)"),
    CODE_437("437", "Rejeição: CNPJ da instituição de pagamento inválido (NT 2020.006)"),
    CODE_438("438", "Rejeição: Obrigatória as informações do intermediador da transação para operação por site de terceiros (NT 2020.006)"),
    CODE_439("439", "Rejeição: Informações do intermediador da transação para operação por site de terceiros preenchido indevidamente (NT 2020.006)"),
    CODE_440("440", "Rejeição: CNPJ do intermediador da transação inválido (NT 2020.006)"),
    CODE_450("450", "Rejeição: Modelo da NF-e diferente de 55"),
    CODE_451("451", "Rejeição: Processo de Emissão pelo Fisco incompatível com a Série da NF"),
    CODE_453("453", "Rejeição: Ano de inutilização não pode ser superior ao Ano atual"),
    CODE_454("454", "Rejeição: Ano de inutilização não pode ser inferior a 2006"),
    CODE_455("455", "Rejeição: Órgão Autor do evento diferente da UF da Chave de Acesso"),
    CODE_461("461", "Rejeição: Informado campos de percentual de GLP e/ou GLGNn e/ou GLGNi para produto diferente de GLP [nItem: 999]"),
    CODE_462("462", "Rejeição: Código Identificador do CSC no QR-Code não cadastrado na SEFAZ"),
    CODE_463("463", "Rejeição: Código Identificador do CSC no QR-Code foi revogado pela empresa"),
    CODE_464("464", "Rejeição: Código de Hash no QR-Code difere do calculado"),
    CODE_465("465", "Rejeição: Número de Controle da FCI inexistente"),
    CODE_466("466", "Rejeição: Evento com Tipo de Autor incompatível"),
    CODE_467("467", "Rejeição: Dados da NF-e divergentes do EPEC [tag: xxxx]"),
    CODE_468("468", "Rejeição: NF-e com Tipo Emissão = 4, sem EPEC correspondente"),
    CODE_471("471", "Rejeição: Informado NCM=00 indevidamente"),
    CODE_472("472", "Rejeição: CPF consultado difere do CPF do Certificado Digital"),
    CODE_476("476", "Rejeição: Código da UF diverge da UF da primeira NF-e do Lote"),
    CODE_477("477", "Rejeição: Código do órgão diverge do órgão do primeiro evento do Lote"),
    CODE_478("478", "Rejeição: Local da entrega não informado para faturamento direto de veículos novos"),
    CODE_479("479", "Rejeição: Data de Emissão anterior a data de credenciamento ou anterior a Data de Abertura do estabelecimento"),
    CODE_480("480", "Rejeição: Código Município do Emitente diverge do cadastrado na UF"),
    CODE_481("481", "Rejeição: Código Regime Tributário do emitente diverge do cadastro na SEFAZ"),
    CODE_482("482", "Rejeição: Código do Município do Destinatário diverge do cadastrado na UF"),
    CODE_483("483", "Rejeição: Valor do desconto maior que valor do produto [nItem: nnn]"),
    CODE_484("484", "Rejeição: Chave de Acesso com tipo de emissão diferente de 4 (posição 35 da Chave de Acesso)"),
    CODE_485("485", "Rejeição: Duplicidade de numeração do EPEC (Modelo, CNPJ ou CPF, Série e Número)"),
    CODE_486("486", "Rejeição: Não informado o Grupo de Autorização para UF que exige a identificação do Escritório de Contabilidade na Nota Fiscal"),
    CODE_487("487", "Rejeição: Escritório de Contabilidade não cadastrado na SEFAZ"),
    CODE_488("488", "Rejeição: Vendas do Emitente incompatíveis com o Porte da Empresa"),
    CODE_489("489", "Rejeição: CNPJ informado inválido (DV ou zeros)"),
    CODE_490("490", "Rejeição: CPF informado inválido (DV ou zeros)"),
    CODE_491("491", "Rejeicao: O tpEvento informado invalido"),
    CODE_494("494", "Rejeição: Chave de Acesso inexistente [chNFe:99999999999999999999999999999999999999999999]"),
    CODE_495("495", "Rejeição: CPF do Emitente com Série incompatível"),
    CODE_501("501", "Rejeição: Prazo de cancelamento superior ao previsto na Legislação"),
    CODE_502("502", "Rejeição: Erro na Chave de Acesso - Campo Id não corresponde à concatenação dos campos correspondentes"),
    CODE_503("503", "Rejeição: CNPJ do emitente com Série incompatível"),
    CODE_504("504", "Rejeição: Data de Entrada/Saída posterior ao permitido"),
    CODE_505("505", "Rejeição: Data de Entrada/Saída anterior ao permitido"),
    CODE_506("506", "Rejeição: Data de Saída menor que a Data de Emissão"),
    CODE_508("508", "Rejeição: CST incompatível na operação com Não Contribuinte [nItem: 999]"),
    CODE_509("509", "Rejeição: Informado código de município diferente de “9999999” para operação com o exterior"),
    CODE_510("510", "Rejeição: Operação com Exterior e Código País destinatário é 1058 (Brasil) ou não informado"),
    CODE_511("511", "Rejeição: Não é de Operação com Exterior e Código País destinatário difere de 1058 (Brasil)"),
    CODE_512("512", "Rejeição: CNPJ do Local de Retirada inválido"),
    CODE_513("513", "Rejeição: Código Município do Local de Retirada deve ser 9999999 para UF retirada = “EX”."),
    CODE_514("514", "Rejeição: CNPJ do Local de Entrega inválido"),
    CODE_515("515", "Rejeição: Código Município do Local de Entrega deve ser 9999999 para UF entrega = “EX”."),
    CODE_516("516", "Rejeição: Falha no schema XML – inexiste a tag raiz esperada para a mensagem"),
    CODE_517("517", "Rejeição: Falha no schema XML – inexiste atributo versao na tag raiz da mensagem"),
    CODE_518("518", "Rejeição: CFOP de entrada para NF-e de saída"),
    CODE_519("519", "Rejeição: CFOP de saída para NF-e de entrada"),
    CODE_520("520", "Rejeição: CFOP de Operação com Exterior e UF destinatário difere de “EX”"),
    CODE_521("521", "Rejeição: Operação Interna e UF do emitente difere da UF do destinatário/remetente contribuinte do ICMS"),
    CODE_522("522", "Rejeição: Chave de Acesso referenciada com UF inválida[nOcor:nnn]"),
    CODE_523("523", "Rejeição: CFOP não é de Operação Estadual e UF emitente igual à UF destinatário [nItem: 999]"),
    CODE_524("524", "Rejeição: Chave de Acesso referenciada com Ano-Mês inválido [nOcor: 999]"),
    CODE_525("525", "Rejeição: CFOP de Importação e não informado dados da DI [nItem: 999]"),
    CODE_526("526", "Rejeição: Consulta a uma Chave de Acesso muito antiga"),
    CODE_527("527", "Rejeição: Operação de Exportação com informação de ICMS incompatível"),
    CODE_528("528", "Rejeição: Valor do ICMS difere do produto BC e Alíquota [nItem: 999]"),
    CODE_529("529", "Rejeição: CST incompatível na operação com Contribuinte Isento de Inscrição Estadual [nItem: 999]"),
    CODE_530("530", "Rejeição: Operação com tributação de ISSQN sem informar a Inscrição Municipal"),
    CODE_531("531", "Rejeição: Total da BC ICMS difere do somatório dos itens"),
    CODE_532("532", "Rejeição: Total do ICMS difere do somatório dos itens"),
    CODE_533("533", "Rejeição: Total da BC ICMS-ST difere do somatório dos itens"),
    CODE_534("534", "Rejeição: Total do ICMS-ST difere do somatório dos itens"),
    CODE_535("535", "Rejeição: Total do Frete difere do somatório dos itens"),
    CODE_536("536", "Rejeição: Total do Seguro difere do somatório dos itens"),
    CODE_537("537", "Rejeição: Total do Desconto difere do somatório dos itens"),
    CODE_538("538", "Rejeição: Total do IPI difere do somatório dos itens"),
    CODE_539("539", "Rejeição: Duplicidade de NF-e com diferença na Chave de Acesso [chNFe: 99999999999999999999999999999999999999999999][nRec:999999999999999]"),
    CODE_540("540", "Rejeição: CPF do Local de Retirada inválido"),
    CODE_541("541", "Rejeição: CPF do Local de Entrega inválido"),
    CODE_542("542", "Rejeição: CNPJ do Transportador inválido"),
    CODE_543("543", "Rejeição: CPF do Transportador inválido"),
    CODE_544("544", "Rejeição: IE do Transportador inválida"),
    CODE_547("547", "Rejeição: Chave de Acesso referenciada com Dígito Verificador inválido[nOcor:nnn]"),
    CODE_548("548", "Rejeição: NF modelo 1 referenciada com data de emissão inválida [nOcor:nnn]"),
    CODE_549("549", "Rejeição: CNPJ da NF referenciada de produtor inválido [nOcor: 999]"),
    CODE_550("550", "Rejeição: CPF da NF referenciada de produtor inválido."),
    CODE_551("551", "Rejeição: IE da NF referenciada de produtor inválido."),
    CODE_552("552", "Rejeição: Chave de Acesso referenciada com CNPJ/CPF inválido[nOcor:nnn]"),
    CODE_553("553", "Rejeição: Tipo autorizador do recibo diverge do Órgão Autorizador."),
    CODE_554("554", "Rejeição: IE do Emitente informada como ISENTO indevidamente"),
    CODE_556("556", "Rejeição: Justificativa de entrada em contingência não deve ser informada para tipo de emissão normal"),
    CODE_557("557", "Rejeição: A Justificativa de entrada em contingência deve ser informada"),
    CODE_558("558", "Rejeição: Data de entrada em contingência posterior a data de recebimento"),
    CODE_559("559", "Rejeição: UF do Transportador não informada"),
    CODE_560("560", "Rejeição: CNPJ base/CPF do emitente difere do CNPJ base/CPF da primeira NF-e do lote recebido"),
    CODE_561("561", "Rejeição: Mês de Emissão informado na Chave de Acesso difere do Mês de Emissão da NF-e"),
    CODE_562("562", "Rejeição: Código Numérico informado na Chave de Acesso difere do Código Numérico da NF-e [chNFe:99999999999999999999999999999999999999999999"),
    CODE_563("563", "Rejeição: Já existe pedido de Inutilização com a mesma faixa de inutilização"),
    CODE_564("564", "Rejeição: Total do Produto / Serviço difere do somatório dos itens"),
    CODE_565("565", "Rejeição: Falha no schema XML – inexiste a tag raiz esperada para o lote de NF-e"),
    CODE_568("568", "Rejeição: Falha no schema XML – inexiste atributo versao na tag raiz do lote de NF-e"),
    CODE_569("569", "Rejeição: Data de entrada em contingência muito atrasada"),
    CODE_570("570", "Rejeição: Tipo de Emissão 3, 6 ou 7 só é válido nas contingências SCAN/SVC"),
    CODE_571("571", "Rejeição: Processo de emissão pelo Fisco com Certificado de Transmissão incompatível"),
    CODE_572("572", "Rejeição: Erro Atributo ID do evento não corresponde a concatenação dos campos (“ID” + tpEvento + chNFe + nSeqEvento)"),
    CODE_573("573", "Rejeição: Duplicidade de Evento"),
    CODE_574("574", "Rejeição: O autor do evento diverge do emissor da NF-e"),
    CODE_575("575", "Rejeição: O autor do evento diverge do destinatário da NF-e"),
    CODE_576("576", "Rejeição: O autor do evento não é um órgão autorizado a gerar o evento"),
    CODE_577("577", "Rejeição: A data do evento não pode ser menor que a data de emissão da NF-e"),
    CODE_578("578", "Rejeição: A data do evento não pode ser maior que a data do processamento"),
    CODE_579("579", "Rejeição: A data do evento não pode ser menor que a data de autorização para NF-e não emitida em contingência"),
    CODE_580("580", "Rejeição: O evento exige uma NF-e autorizada"),
    CODE_582("582", "Rejeicao: UF nao atendida pela SVC-[AN/RS]"),
    CODE_584("584", "Rejeição: tpEmis informado é incompatível com a SVC-[AN/RS]"),
    CODE_587("587", "Rejeição: Usar somente o namespace padrão da NF-e"),
    CODE_588("588", "Rejeição: Não é permitida a presença de caracteres de edição no início/fim da mensagem ou entre as tags da mensagem"),
    CODE_589("589", "Rejeição: Número do NSU informado superior ao maior NSU do Ambiente Nacional"),
    CODE_590("590", "Rejeição: Informado CST para emissor do Simples Nacional (CRT=1)"),
    CODE_591("591", "Rejeição: Informado CSOSN para emissor que não é do Simples Nacional (CRT diferente de 1)"),
    CODE_592("592", "Rejeição: A NF-e deve ter pelo menos um item de produto sujeito ao ICMS."),
    CODE_593("593", "Rejeição: CNPJ-Base consultado difere do CNPJ-Base do Certificado Digital"),
    CODE_594("594", "Rejeição: O número de sequencia do evento informado é maior que o permitido"),
    CODE_595("595", "Rejeição: Obrigatória a informação da justificativa do evento."),
    CODE_596("596", "Rejeição: Evento apresentado fora do prazo: [prazo vigente]"),
    CODE_597("597", "Rejeição: CFOP de Importação e não informado dados de IPI"),
    CODE_598("598", "Rejeição: NF-e emitida em ambiente de homologação com Razão Social do destinatário diferente de NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL"),
    CODE_599("599", "Rejeição: CFOP de Importação e não informado dados de II [nItem: 999]"),
    CODE_600("600", "Rejeição: CSOSN incompatível na operação com Não Contribuinte [nItem: 999]"),
    CODE_601("601", "Rejeição: Total do II difere do somatório dos itens"),
    CODE_602("602", "Rejeição: Total do PIS difere do somatório dos itens sujeitos ao ICMS"),
    CODE_603("603", "Rejeição: Total da COFINS difere do somatório dos itens sujeitos ao ICMS"),
    CODE_604("604", "Rejeição: Total do vOutro difere do somatório dos itens"),
    CODE_605("605", "Rejeição: Total do vServ difere do somatório do vProd dos itens sujeitos ao ISSQN"),
    CODE_606("606", "Rejeição: Total do vBC do ISS difere do somatório dos itens"),
    CODE_607("607", "Rejeição: Total do ISS difere do somatório dos itens"),
    CODE_608("608", "Rejeição: Total do PIS difere do somatório dos itens sujeitos ao ISSQN"),
    CODE_609("609", "Rejeição: Total da COFINS difere do somatório dos itens sujeitos ao ISSQN"),
    CODE_610("610", "Rejeição: Total da NF difere do somatório dos Valores compõe o valor Total da NF."),
    CODE_611("611", "Rejeição: GTIN (cEAN) inválido [nItem:999]"),
    CODE_612("612", "Rejeição: GTIN da unidade tributável (cEANTrib) inválido [nItem:999]"),
    CODE_613("613", "Rejeição: Chave de Acesso difere da existente em BD"),
    CODE_614("614", "Rejeição: Chave de Acesso inválida (Código UF inválido)"),
    CODE_615("615", "Rejeição: Chave de Acesso inválida (Ano < 06 ou Ano maior que Ano Corrente)"),
    CODE_616("616", "Rejeição: Chave de Acesso inválida (Mês < 1 ou Mês > 12)"),
    CODE_617("617", "Rejeição: Chave de Acesso inválida (CNPJ/CPF zerado ou dígito inválido)"),
    CODE_618("618", "Rejeição: Chave de Acesso inválida (modelo diferente de 55 e 65)"),
    CODE_619("619", "Rejeição: Chave de Acesso inválida (número NF = 0)"),
    CODE_621("621", "Rejeição: CPF Emitente não cadastrado"),
    CODE_622("622", "Rejeição: IE emitente não vinculada ao CPF"),
    CODE_623("623", "Rejeição: CPF Destinatário não cadastrado"),
    CODE_624("624", "Rejeição: IE Destinatário não vinculada ao CPF"),
    CODE_625("625", "Rejeição: Inscrição SUFRAMA deve ser informada na venda com isenção para ZFM [nItem: 999]"),
    CODE_626("626", "Rejeição: CFOP de operação isenta para ZFM diferente do previsto [nItem: 999]"),
    CODE_627("627", "Rejeição: O valor do ICMS desonerado deve ser informado [nItem: 999]"),
    CODE_628("628", "Rejeição: Total da NF superior ao valor limite estabelecido pela SEFAZ [Limite]"),
    CODE_629("629", "Rejeição: Valor do Produto difere do produto Valor Unitário de Comercialização e Quantidade Comercial [nItem: 999]"),
    CODE_630("630", "Rejeição: Valor do Produto difere do produto Valor Unitário de Tributação e Quantidade Tributável [nItem: 999]"),
    CODE_631("631", "Rejeição: CNPJ-Base do Destinatário difere do CNPJ-Base do Certificado Digital"),
    CODE_632("632", "Rejeição: Solicitação fora de prazo, a NF-e não está mais disponível para download"),
    CODE_633("633", "Rejeição: NF-e indisponível para download devido a ausência de Manifestação do Destinatário"),
    CODE_634("634", "Rejeição: Destinatário da NF-e não tem o mesmo CNPJ raiz do solicitante do download"),
    CODE_635("635", "Rejeição: NF-e com mesmo número e série já transmitida e aguardando processamento"),
    CODE_636("636", "Rejeição: O tipo do evento de cancelamento não corresponde ao tipo do evento a ser cancelado"),
    CODE_638("638", "Rejeição: A quantidade de Pedidos de Prorrogação 1º prazo excede o valor limite de 20 Pedidos de Prorrogação autorizados e sem resposta do Fisco"),
    CODE_639("639", "Rejeição: A quantidade de Pedidos de Prorrogação 2° prazo excede o valor limite de 20 Pedidos de Prorrogação autorizados e sem resposta do Fisco."),
    CODE_640("640", "Rejeição: CNPJ/CPF do interessado não possui permissão para consultar esta NF-e"),
    CODE_640_2("640", "Rejeição: ID do Pedido de Prorrogação inválido"),
    CODE_641("641", "Rejeição: A data do evento não pode ser menor que a data de autorização para o evento"),
    CODE_641_2("641", "Rejeição: NF-e indisponível para o emitente"),
    CODE_650("650", "Rejeição: Evento de \"Ciência da Emissão\" para NF-e Cancelada ou Denegada"),
    CODE_651("651", "Rejeição: Evento de \"Desconhecimento da Operação\" para NF-e Cancelada ou Denegada"),
    CODE_652("652", "Rejeição: NF-e para emitente pessoa física"),
    CODE_653("653", "Rejeição: NF-e Cancelada, arquivo indisponível para download"),
    CODE_654("654", "Rejeição: NF-e Denegada, arquivo indisponível para download"),
    CODE_655("655", "Rejeição: Evento de Ciência da Emissão informado após a manifestação final do destinatário"),
    CODE_656("656", "Rejeição: Consumo indevido pelo aplicativo da empresa [det: DESC_ERRO]"),
    CODE_657("657", "Rejeição: Código do Órgão diverge do órgão autorizador"),
    CODE_658("658", "Rejeição: UF do destinatário da Chave de Acesso diverge da UF autorizadora"),
    CODE_659("659", "Rejeição: Ano-Mês da Data de Emissão diverge do Ano_Mês da Chave de Acesso"),
    CODE_660("660", "Rejeição: CFOP de Combustível e não informado grupo de combustível da NF-e [nItem: nnn]"),
    CODE_661("661", "Rejeição: NF-e já existente para o número do EPEC informado"),
    CODE_662("662", "Rejeição: Numeração do EPEC está inutilizada na Base de Dados da SEFAZ"),
    CODE_663("663", "Rejeição: Alíquota do ICMS com valor superior a 4 por cento na operação de saída interestadual com produtos importados [nItem: 999]"),
    CODE_678("678", "Rejeição: NF referenciada com UF diferente da NF-e complementar"),
    CODE_679("679", "Rejeição: Chave de Acesso referenciada com Modelo inválido[nOcor:nnn]"),
    CODE_680("680", "Rejeição: Chave de Acesso referenciada em duplicidade na NF-e [nOcor:nnn]"),
    CODE_681("681", "Rejeição: Duplicidade de NF Modelo 1 referenciada (CNPJ, Modelo, Série e Número) [nOcor: nnn]"),
    CODE_682("682", "Rejeição: Duplicidade de NF de Produtor referenciada (IE, Modelo, Série e Número) [nOcor: 999]"),
    CODE_683("683", "Rejeição: Chave de Acesso referenciada com Número inválido[nOcor:nnn]"),
    CODE_684("684", "Rejeição: Duplicidade de Cupom Fiscal referenciado (Modelo, Número de Ordem e COO) [nOcor: 999]"),
    CODE_685("685", "Rejeição: Total do Valor Aproximado dos Tributos difere do somatório dos itens"),
    CODE_686("686", "Rejeição: NF Complementar referencia uma NF-e cancelada"),
    CODE_687("687", "Rejeição: NF Complementar referencia uma NF-e denegada"),
    CODE_688("688", "Rejeição: NF referenciada de Produtor com IE inexistente [nRef: xxx]"),
    CODE_689("689", "Rejeição: NF referenciada de Produtor com IE não vinculada ao CNPJ/CPF informado [nRef: xxx]"),
    CODE_690("690", "Rejeição: Pedido de Cancelamento para NF-e com CT-e ou MDF-e"),
    CODE_691("691", "Rejeição: Chave de Acesso da NF-e diverge da Chave de Acesso do EPEC [Chave EPEC: xxxxxxxxx]"),
    CODE_692("692", "Rejeição: Existe EPEC registrado para esta Série e Número [Chave EPEC: xxxxxxxxxxx]"),
    CODE_693("693", "Rejeição: Alíquota de ICMS superior à definida para a operação interestadual [nItem: 999]"),
    CODE_694("694", "Rejeição: Não informado o grupo de ICMS para a UF de destino [nItem: 999]"),
    CODE_695("695", "Rejeição: Informado indevidamente o grupo de ICMS para a UF de destino [nItem:999]"),
    CODE_696("696", "Rejeição: Operação com não contribuinte deve indicar operação com consumidor final"),
    CODE_697("697", "Rejeição: Alíquota interestadual do ICMS com origem diferente do previsto [nItem:999]"),
    CODE_698("698", "Rejeição: Alíquota interestadual do ICMS incompatível com as UF envolvidas na operação [nItem:999]"),
    CODE_699("699", "Rejeição: Percentual do ICMS Interestadual para a UF de destino difere do previsto para o ano da Data de Emissão [nItem: 999]"),
    CODE_700("700", "Rejeição: Total da quantidade tributada do ICMS monofásico próprio difere do somatório dos itens."),
    CODE_701("701", "Rejeição: Não informado Nota Fiscal referenciada (CFOP de Exportação Indireta) [nItem: nnn]"),
    CODE_701_2("701", "Rejeição: Não informado Nota Fiscal referenciada (Lançamento relativo a Cupom Fiscal) [nItem: nnn]"),
    CODE_702("702", "Rejeição: NFC-e não é aceita pela UF do Emitente"),
    CODE_703("703", "Rejeição: Data-Hora de Emissão posterior ao horário de recebimento"),
    CODE_704("704", "Rejeição: NFC-e com Data-Hora de emissão atrasada"),
    CODE_705("705", "Rejeição: NFC-e com data de entrada/saída"),
    CODE_706("706", "Rejeição: NFC-e para operação de entrada"),
    CODE_707("707", "Rejeição: NFC-e para operação interestadual ou com o exterior"),
    CODE_708("708", "Rejeição: NFC-e não pode referenciar documento fiscal"),
    CODE_709("709", "Rejeição: NFC-e com formato de DANFE inválido"),
    CODE_710("710", "Rejeição: NF-e com formato de DANFE inválido"),
    CODE_711("711", "Rejeição: NF-e com contingência off-line"),
    CODE_712("712", "Rejeição: NFC-e com contingência off-line para a UF"),
    CODE_713("713", "Rejeição: Tipo de Emissão diferente de 6 ou 7 para contingência da SVC acessada"),
    CODE_714("714", "Rejeição: NFC-e com contingência inválida (tpEmis=2, 4 (a critério da UF) ou 5)"),
    CODE_715("715", "Rejeição: NFC-e com finalidade inválida"),
    CODE_716("716", "Rejeição: NFC-e em operação não destinada a consumidor final"),
    CODE_717("717", "Rejeição: NFC-e em operação não presencial"),
    CODE_718("718", "Rejeição: NFC-e não deve informar IE de Substituto Tributário"),
    CODE_719("719", "Rejeição: NF-e sem a identificação do destinatário"),
    CODE_720("720", "Rejeição: Na operação com Exterior deve ser informada tag idEstrangeiro"),
    CODE_721("721", "Rejeição: Informado idEstrangeiro e Operação não é com consumidor final."),
    CODE_721_2("721", "Rejeição: Operação interestadual deve informar CNPJ ou CPF"),
    CODE_722("722", "Rejeição: CFOP de Transporte Inexistente"),
    CODE_723("723", "Rejeição: Total da quantidade tributada do ICMS monofásico sujeito a retenção difere do somatório dos itens."),
    CODE_724("724", "Rejeição: NF-e sem o nome do destinatário"),
    CODE_725("725", "Rejeição: NFC-e com CFOP inválido[nItem:nnn]"),
    CODE_726("726", "Rejeição: NF-e sem a informação de endereço do destinatário"),
    CODE_727("727", "Rejeição: Operação com Exterior e UF diferente de EX"),
    CODE_728("728", "Rejeição: NF-e sem informação da IE do destinatário"),
    CODE_729("729", "Rejeição: NFC-e com informação da IE do destinatário"),
    CODE_730("730", "Rejeição: NFC-e com Inscrição Suframa"),
    CODE_731("731", "Rejeição: CFOP de operação com Exterior e idDest <> 3"),
    CODE_732("732", "Rejeição: CFOP de operação interestadual e idDest <> 2"),
    CODE_733("733", "Rejeição: CFOP de operação interna e idDest <> 1"),
    CODE_734("734", "Rejeição: NFC-e com Unidade de Comercialização inválida [nItem: 999]"),
    CODE_735("735", "Rejeição: NFC-e com Unidade de Tributação inválida [nItem: 999]"),
    CODE_736("736", "Rejeição: NFC-e com grupo de Veículos novos"),
    CODE_737("737", "Rejeição: Pagamento com cartão de crédito em sistema de automação não integrado"),
    CODE_738("738", "Rejeição: NFC-e com grupo de Armamentos"),
    CODE_739("739", "Rejeição: Código de País do ISSQN Inexistente"),
    CODE_740("740", "Rejeição: Item com Repasse de ICMS retido por Substituto Tributário [nItem: nnn]"),
    CODE_741("741", "Rejeição: NFC-e com Partilha de ICMS entre UF"),
    CODE_742("742", "Rejeição: NFC-e com grupo do IPI"),
    CODE_743("743", "Rejeição: NFC-e com grupo do II"),
    CODE_744("744", "Rejeição: Total da quantidade tributada do ICMS monofásico retido anteriormente difere do somatório dos itens."),
    CODE_745("745", "Rejeição: NF-e sem grupo do PIS"),
    CODE_746("746", "Rejeição: NFC-e com grupo do PIS-ST"),
    CODE_748("748", "Rejeição: NF-e sem grupo da COFINS"),
    CODE_747("747", "Rejeição: Não permitido o preenchimento do grupo de UF de origem do combustível [nItem:999]"),
    CODE_749("749", "Rejeição: NFC-e com grupo da COFINS-ST"),
    CODE_750("750", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Código) [Limite]"),
    CODE_751("751", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Nome) [Limite]"),
    CODE_752("752", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Endereço) [Limite]"),
    CODE_753("753", "Rejeição: NFC-e com Frete"),
    CODE_754("754", "Rejeição: NFC-e com dados do Transportador"),
    CODE_755("755", "Rejeição: NFC-e com dados de Retenção do ICMS no Transporte"),
    CODE_756("756", "Rejeição: NFC-e com dados do veículo de Transporte"),
    CODE_757("757", "Rejeição: NFC-e com dados de Reboque do veículo de Transporte"),
    CODE_758("758", "Rejeição: NFC-e com dados do Vagão de Transporte"),
    CODE_759("759", "Rejeição: NFC-e com dados da Balsa de Transporte"),
    CODE_760("760", "Rejeição: NFC-e com dados de cobrança (Fatura, Duplicata)"),
    CODE_761("761", "Rejeição: Código de Produto ANP inexistente [nItem: 999]"),
    CODE_762("762", "Rejeição: NFC-e com dados de compras (Empenho, Pedido, Contrato)"),
    CODE_763("763", "Rejeição: NFC-e com dados de aquisição de Cana"),
    CODE_765("765", "Rejeição: Lote só poderá conter NF-e ou NFC-e"),
    CODE_766("766", "Rejeição: Item com CST indevido [nItem:nnn]"),
    CODE_770("770", "Rejeição: CFOP Inexistente [nItem:nnn]"),
    CODE_771("771", "Rejeição: Informado idEstrangeiro em operação interestadual"),
    CODE_772("772", "Rejeição: Operação Interestadual e UF de destino igual à UF de origem"),
    CODE_773("773", "Rejeição: Operação Interna e UF de destino difere da UF de origem"),
    CODE_774("774", "Rejeição: NFC-e com indicador de item não participante do total [nItem: 999]"),
    CODE_775("775", "Rejeição: Modelo da NFC-e diferente de 65"),
    CODE_776("776", "Rejeicao: UF não disponibiliza este atendimento"),
    CODE_777("777", "Rejeição: Obrigatória a informação do NCM completo (redação dada pela NT 2013/005 v 1.20) [nItem: 999]"),
    CODE_778("778", "Rejeição: Informado NCM inexistente[nItem:nnn]"),
    CODE_779("779", "Rejeição: NFC-e com NCM incompatível [nItem: 999]"),
    CODE_780("780", "Rejeição: Total da NFC-e superior ao valor limite estabelecido pela SEFAZ [Limite]"),
    CODE_781("781", "Rejeição: Emissor não habilitado para emissão da NFC-e"),
    CODE_783("783", "Rejeição: NFC-e não é autorizada pela SVC"),
    CODE_784("784", "Rejeição: NFC-e não permite o evento de Carta de Correção"),
    CODE_785("785", "Rejeição: NFC-e com entrega a domicílio não permitida pela UF"),
    CODE_786("786", "Rejeição: NFC-e de entrega a domicílio sem dados do Transportador"),
    CODE_787("787", "Rejeição: NFC-e de entrega a domicílio sem a identificação do destinatário"),
    CODE_788("788", "Rejeição: NFC-e de entrega a domicílio sem o endereço do destinatário"),
    CODE_789("789", "Rejeição: NFC-e para destinatário contribuinte de ICMS"),
    CODE_790("790", "Rejeição: Operação com Exterior para destinatário Contribuinte de ICMS"),
    CODE_791("791", "Rejeição: NF-e com indicação de destinatário isento de IE, com a informação da IE do destinatário"),
    CODE_792("792", "Rejeição: Informada a IE do destinatário para operação com destinatário no Exterior"),
    CODE_793("793", "Rejeição: Valor do ICMS relativo ao Fundo de Combate à Pobreza na UF de destino difere do calculado [nItem: 999]"),
    CODE_794("794", "Rejeição: NF-e com indicativo de NFC-e com entrega a domicílio"),
    CODE_795("795", "Rejeição: Total do ICMS desonerado difere do somatório dos itens"),
    CODE_798("798", "Rejeição: Valor total do ICMS relativo Fundo de Combate à Pobreza (FCP) da UF de destino difere do somatório do valor dos itens"),
    CODE_799("799", "Rejeição: Valor total do ICMS Interestadual da UF de destino difere do somatório dos itens"),
    CODE_800("800", "Rejeição: Valor total do ICMS Interestadual da UF do remetente difere do somatório dos itens"),
    CODE_805("805", "Rejeição: A SEFAZ do destinatário não permite Contribuinte Isento de Inscrição Estadual"),
    CODE_806("806", "Rejeição: Operação com ICMS-ST sem informação do CEST [nItem: 999]"),
    CODE_807("807", "Rejeição: NFC-e com grupo de ICMS para a UF do destinatário"),
    CODE_811("811", "Rejeição: Pedido de Prorrogação deferido impede o cancelamento da NF-e"),
    CODE_812("812", "Rejeição: Regime Tributário SN, com excesso de sublimite não é permitido para Emitentes desta UF"),
    CODE_813("813", "Rejeição: QR-Code com sequência de escape para o e-comercial. Usar CDATA"),
    CODE_814("814", "Rejeição: Nota Fiscal com grupo de comércio exterior"),
    CODE_815("815", "Rejeição: Valor do ICMS Interestadual para UF de Destino difere do calculado [nItem: 999] (Valor Informado: XXX, Valor Calculado:XXX)"),
    CODE_816("816", "Rejeição: Valor do ICMS Interestadual para UF do Remetente difere do calculado [nItem: 999] (Valor Informado: XXX, Valor Calculado:XXX)"),
    CODE_817("817", "Rejeição: Unidade Tributável incompatível com o NCM informado na operação com Comércio Exterior [nItem: 999]"),
    CODE_827("827", "Rejeição: Obrigatório informar o tipo de autorização"),
    CODE_828("828", "Rejeição: Não permitido informar o campo tipo de autorização"),
    CODE_829("829", "Rejeição: Condição de uso não informado para o tipo de autorização de uso"),
    CODE_830("830", "Rejeição: Não permitido preencher o campo Condição de Uso"),
    CODE_850("850", "Rejeição: Data de vencimento da parcela não informada ou menor que a Data de vencimento da parcela anterior [nOcor: 999]"),
    CODE_851("851", "Rejeição: Soma do valor das parcelas difere do Valor Líquido da Fatura"),
    CODE_852("852", "Rejeição: Número da parcela inválido ou não informado [nOcor: 999]"),
    CODE_854("854", "Rejeição: Unidade Tributável (tag:uTrib) incompatível com produto informado [nItem: 999]"),
    CODE_855("855", "Rejeição: Somatório percentuais de GLP derivado do petróleo, GLGNn e GLGNi diferente de 100 [nItem: 999]."),
    CODE_856("856", "Rejeição: Campo valor de partida não preenchido para produto GLP [nItem: 999]."),
    CODE_857("857", "Rejeição: Informado Duplicata Mercantil como Forma de Pagamento"),
    CODE_858("858", "Rejeição: Grupo de Tributação informado indevidamente [nItem: 999]"),
    CODE_859("859", "Rejeição: Total do FCP retido anteriormente por Substituição Tributária difere do somatório dos itens"),
    CODE_860("860", "Rejeição: Valor do FCP informado difere de base de cálculo*alíquota [nItem: 999]"),
    CODE_861("861", "Rejeição: Total do FCP difere do somatório dos itens"),
    CODE_862("862", "Rejeição: Total do FCP ST difere do somatório dos itens"),
    CODE_863("863", "Rejeição: Total do IPI devolvido difere do somatório dos itens"),
    CODE_864("864", "Rejeição: NF-e com indicativo de Operação presencial, fora do estabelecimento e não informada NF referenciada"),
    CODE_865("865", "Rejeição: Total dos pagamentos menor que o total da nota"),
    CODE_866("866", "Rejeição: Ausência de troco quando o valor dos pagamentos informados for maior que o total da nota"),
    CODE_868("868", "Rejeição: Grupos Veiculo Transporte e Reboque não devem ser informados"),
    CODE_869("869", "Rejeição: Valor do troco incorreto"),
    CODE_870("870", "Rejeição: Data de validade incompatível com data de fabricação [nItem: 999]"),
    CODE_871("871", "Rejeição: O campo Meio de Pagamento deve ser preenchido com a opção Sem Pagamento"),
    CODE_873("873", "Rejeição: Operação com medicamentos e não informado os campos de rastreabilidade [nItem: 999]"),
    CODE_874("874", "Rejeição: Percentual de FCP inválido [nItem: 999]"),
    CODE_875("875", "Rejeição: Percentual de FCPST inválido [nItem: 999]"),
    CODE_876("876", "Rejeição: Operação interestadual para Consumidor Final e valor do FCP informado em campo diferente de vFCPUFDest (id:NA13) [nItem: 999]"),
    CODE_877("877", "Rejeição: Data de fabricação maior que a data de processamento [nItem: 999]"),
    CODE_878("878", "Rejeição: Endereço do site da UF da Consulta por chave de acesso diverge do previsto"),
    CODE_879("879", "Rejeição: Informado item “Produzido em Escala NÃO Relevante” e não informado CNPJ do Fabricante [nItem: 999]"),
    CODE_880("880", "Rejeição: Percentual de FCP igual a zero [nItem: 999]"),
    CODE_881("881", "Rejeição: Percentual de FCPST igual a zero [nItem: 999]"),
    CODE_882("882", "Rejeição: GTIN (cEAN) com prefixo inválido [nItem:999]"),
    CODE_883("883", "Rejeição: GTIN (cEAN) sem informação [nItem: 999]"),
    CODE_884("884", "Rejeição: GTIN da unidade tributável (cEANTrib) com prefixo inválido [nItem:999]"),
    CODE_885("885", "Rejeição: GTIN informado, mas não informado o GTIN da unidade tributável [nItem:999]"),
    CODE_886("886", "Rejeição: GTIN da unidade tributável informado, mas não informado o GTIN [nItem:999]"),
    CODE_888("888", "Rejeição: GTIN da unidade tributável (cEANTrib) sem informação [nItem:999]"),
    CODE_889("889", "Rejeição: Obrigatória a informação do GTIN para o produto [nItem: 999]"),
    CODE_890("890", "Rejeição: GTIN inexistente no Cadastro Centralizado de GTIN (CCG) [nItem:999]"),
    CODE_891("891", "Rejeição: GTIN incompatível com a NCM [nItem:999; NCM esperada: 99999999]"),
    CODE_892("892", "Rejeição: GTIN incompatível com CEST [nItem:999; CEST esperado: 9999999]"),
    CODE_893("893", "Rejeição: GTIN da unidade tributável diverge do GTIN Contido cadastrado no CCG [nItem:999; GTIN Contido esperado: 99999999999999]"),
    CODE_894("894", "Rejeição: GTIN da unidade tributável inexistente no Cadastro Centralizado de GTIN (CCG) [nItem:999]"),
    CODE_895("895", "Rejeição: GTIN da unidade tributável incompatível com a NCM [nItem:999; NCM esperada: 99999999]"),
    CODE_896("896", "Rejeição: GTIN da unidade tributável incompatível com CEST [nItem:999; CEST esperado: 9999999]"),
    CODE_899("899", "Rejeição: Informado incorretamente o campo meio de pagamento"),
    CODE_900("900", "Rejeição: Data de vencimento da parcela não informada ou menor que Data de Emissão [nOcor: 999]"),
    CODE_901("901", "Rejeição: Valor do Desconto da Fatura maior que Valor Original da Fatura"),
    CODE_902("902", "Rejeição: Valor Liquido da Fatura difere do Valor Original menos o Valor do Desconto"),
    CODE_903("903", "Rejeição Versão informada no QR-Code (“100”) não é mais válida para a data de emissão"),
    CODE_904("904", "Rejeição: Informado indevidamente campo valor de pagamento"),
    CODE_905("905", "Rejeição: Campos do grupo Fatura não informados"),
    CODE_906("906", "Rejeição: Não informados os campos para informações do ICMS Efetivo. [nItem: nnn] [NT 2018.005]"),
    CODE_907("907", "Rejeição: Grupo de combustível não pode ter o índice de mistura do Biodiesel. [nItem:999]"),
    CODE_908("908", "Rejeição: Obrigatório o preenchimento do índice de mistura do Biodiesel. [nItem:999]"),
    CODE_909("909", "Rejeição: Obrigatório o preenchimento do grupo de UF de origem do combustível [nItem:999]"),
    CODE_910("910", "Rejeição: Chave de Acesso NF-e Substituta inválida (<nome do campo>) [NT 2018.004]"),
    CODE_911("911", "Rejeição: Chave de Acesso NF-e Substituta incorreta (<nome do campo>) [NT 2018.004]"),
    CODE_912("912", "Rejeição: NF-e Substituta inexistente [NT 2018.004]"),
    CODE_913("913", "Rejeição: NF-e Substituta Denegada ou Cancelada [NT 2018.004]"),
    CODE_914("914", "Rejeição: Data de emissão da NF-e Substituta maior que 2 horas da data de emissão da NF-e a ser cancelada [NT 2018.004]"),
    CODE_915("915", "Rejeição: Valor total da NF-e Substituta difere do valor da NF-e a ser cancelada [NT 2018.004]"),
    CODE_916("916", "Rejeição: Valor total do ICMS da NF-e Substituta difere do valor da NF-e a ser cancelada [NT 2018.004]"),
    CODE_917("917", "Rejeição: Identificação do destinatário da NF-e Substituta difere da identificação do destinatário da NF-e a ser cancelada. [NT2018.004]"),
    CODE_918("918", "Rejeição: Quantidade de itens da NF-e Substituta difere da quantidade de itens da NF-e a ser cancelada. [NT 2018.004]"),
    CODE_919("919", "Rejeição: Item da NF-e Substituta difere do mesmo item da NF-e a ser cancelada. [NT 2018.004]"),
    CODE_920("920", "Rejeição: Tipo de Emissão inválido no Cancelamento por Substituição [NT 2018.004]"),
    CODE_922("922", "Rejeição: Contranota de Produtor só pode referenciar NF-e ou NF de Produtor Modelo 4 [NT 2019.001]"),
    CODE_923("923", "Rejeição: Referenciado documento de operação interna em operação interestadual ou com o exterior [NT 2019.001]"),
    CODE_924("924", "Rejeição: Informado Cupom Fiscal referenciado. [NT 2019.001]"),
    CODE_925("925", "Rejeição: NF-e com identificação de estrangeiro e inscrição estadual informada para destinatário [NT 2019.001]"),
    CODE_926("926", "Rejeição: Operação com Exterior e país de destino igual a Brasil. [NT 2019.001]"),
    CODE_927("927", "Rejeição: Número do item fora da ordem sequencial. [NT 2019.001]"),
    CODE_928("928", "Rejeição: Informado código de benefício fiscal para CST sem benefício fiscal [nItem: nnn] [NT 2019.001]"),
    CODE_929("929", "Rejeição: Informado CST de diferimento sem as informações de diferimento [nItem: nnn] [NT 2019.001]"),
    CODE_930("930", "Rejeição: CST com benefício fiscal e não informado o código de benefício fiscal [nItem: nnn] [NT 2019.001]"),
    CODE_931("931", "Rejeição: CST não corresponde ao tipo de código de benefício fiscal [nItem: nnn] [NT 2019.001]"),
    CODE_932("932", "Rejeição: Informada modalidade de determinação da BC da ST como MVA e não informado o campo pMVAST [nItem: nnn] [NT 2019.001]"),
    CODE_933("933", "Rejeição: Informada modalidade de determinação da BC da ST diferente de MVA e informado o campo pMVAST [nItem: nnn] [NT 2019.001]"),
    CODE_934("934", "Rejeição: Não informado valor do ICMS desonerado ou o Motivo de desoneração [nItem: nnn] [NT 2019.001]"),
    CODE_935("935", "Rejeição: Valor total da Base de Cálculo superior ao valor limite estabelecido [Valor Limite: R$ XXX.XXX,XX] (valor definido pela UF) [NT 2019.001]"),
    CODE_936("936", "Rejeição: Razão Social do emitente diverge do informado no cadastro da SEFAZ"),
    CODE_938("938", "Rejeição: Não informada BCST, pST e ICMSST retido na operação anterior [nItem: 999] [NT 2018.005]"),
    CODE_946("946", "Rejeição: Informado código de benefício fiscal incorreto ou inexistente na UF [nItem: nnn]"),
    CODE_958("958", "Rejeição: Somatório dos percentuais originários para a UF do combustível diverge de 100."),
    CODE_959("959", "Rejeição: NF-e não pode ter preenchimento de Grupo de Tributação do ICMS monofásica sobre combustíveis. [nItem:999]"),
    CODE_960("960", "Rejeição: Obrigatório o preenchimento de Grupo de Tributação do ICMS monofásica sobre combustíveis. [nItem:999]"),
    CODE_961("961", "Rejeição: Alíquota adrem do imposto difere do definido na legislação para o produto. [nItem:999]"),
    CODE_962("962", "Rejeição: Valor do ICMS próprio difere do calculado. [nItem:999]"),
    CODE_963("963", "Rejeição: Alíquota adrem do imposto com retenção difere do definido na legislação para o produto. [nItem:999]"),
    CODE_964("964", "Rejeição: Valor do ICMS com retenção difere do calculado. [nItem:999]"),
    CODE_965("965", "Rejeição: Alíquota adrem do imposto retido anteriormente difere do definido na legislação para o produto. [nItem:999]"),
    CODE_966("966", "Rejeição: Valor do ICMS retido anteriormente difere do calculado. [nItem:999]"),
    CODE_967("967", "Rejeição: Total do ICMS monofásico próprio difere do somatório dos itens."),
    CODE_968("968", "Rejeição: Total do ICMS monofásico sujeito a retenção difere do somatório dos itens."),
    CODE_969("969", "Rejeição: Total do ICMS monofásico retido anteriormente difere do somatório dos itens."),
    CODE_970("970", "Rejeição: Código de País inexistente [local de retirada/entrega] [NT 2018.005]"),
    CODE_971("971", "Rejeição: IE inválida [local de retirada/entrega] [NT 2018.005]"),
    CODE_972("972", "Rejeição: Obrigatória as informações do responsável técnico [NT 2018.005]"),
    CODE_973("973", "Rejeição: CNPJ do responsável técnico inválido [NT 2018.005]"),
    CODE_974("974", "Rejeição: CNPJ do responsável técnico diverge do cadastrado [NT 2018.005]"),
    CODE_975("975", "Rejeição: Obrigatória a informação do identificador do CSRT e do Hash do CSRT [NT 2018.005]"),
    CODE_976("976", "Rejeição: Identificador do CSRT não cadastrado na SEFAZ [NT 2018.005]"),
    CODE_977("977", "Rejeição: Identificador do CSRT revogado [NT 2018.005]"),
    CODE_978("978", "Rejeição: Hash do CSRT diverge do calculado [NT 2018.005]"),
    CODE_999("999", "Rejeição: Erro não catalogado (informar a mensagem de erro capturado no tratamento da exceção)");

    public static final Collection<NFReturnCode> denied = Arrays.asList(CODE_110, CODE_301, CODE_302, CODE_303);
    public static final Collection<NFReturnCode> authorized = Arrays.asList(CODE_100, CODE_150);
    public static final Collection<NFReturnCode> general = Arrays.asList(CODE_101, CODE_102, CODE_135, CODE_136, CODE_151);

    private final String code;
    private final String description;

    public static boolean generateProc(NFReturnCode code) {
        return code.generateProc();
    }

    public static boolean generateProc(String code) {
        try {
            return generateProc(valueOfCode(code));
        } catch (NoEnumException e) {
            log.warn("no enum found for code " + e.getValue());
            return false;
        }
    }

    public static boolean generateProc(Number code) {
        return generateProc(Optional.ofNullable(code).map(Object::toString).orElse(null));
    }

    public static NFReturnCode valueOfCode(String code) {
        return DFEnum.valueOfCode(values(), code);
    }

    public static NFReturnCode valueOfCode(Number code) {
        return valueOfCode(String.valueOf(code));
    }


    @Override
    public Collection<? extends ReturnCode> getDenied() {
        return denied;
    }

    @Override
    public Collection<? extends ReturnCode> getAuthorized() {
        return authorized;
    }

    @Override
    public Collection<? extends ReturnCode> getGeneral() {
        return general;
    }
}
