<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:tns="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento" name="CTeRecepcaoEventoV4">
    <types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"
                   targetNamespace="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento">
            <xs:element name="cteDadosMsg">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:any processContents="lax" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cteRecepcaoEventoResult">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:any processContents="lax" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </types>
    <message name="cteRecepcaoEvento">
        <part name="cteDadosMsg" element="tns:cteDadosMsg"/>
    </message>
    <message name="cteRecepcaoEventoResponse">
        <part name="cteRecepcaoEventoResult" element="tns:cteRecepcaoEventoResult"/>
    </message>
    <portType name="CTeRecepcaoEventoV4Soap12">
        <operation name="cteRecepcaoEvento">
            <input wsam:Action="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento/cteRecepcaoEvento"
                   message="tns:cteRecepcaoEvento"/>
            <output wsam:Action="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento/CTeRecepcaoEventoV4Soap12/cteRecepcaoEventoResponse"
                    message="tns:cteRecepcaoEventoResponse"/>
        </operation>
    </portType>
    <binding name="CTeRecepcaoEventoV4Soap12Binding" type="tns:CTeRecepcaoEventoV4Soap12">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="cteRecepcaoEvento">
            <soap12:operation soapAction="http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcaoEvento/cteRecepcaoEvento"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CTeRecepcaoEventoV4">
        <port name="CTeRecepcaoEventoV4Soap12" binding="tns:CTeRecepcaoEventoV4Soap12Binding">
            <soap12:address location="https://hcte.fazenda.mg.gov.br:443/cte/services/CTeRecepcaoEventoV4"/>
        </port>
    </service>
</definitions>